feat: add teleportTo function to sdk
decentraland/explorer pull request #1023
Opened 2020-06-10 00:04 UTC by pbosio

scene creator can request user to teleport.
test-scene: `0.26.sdk-teleport`
uses:
`teleportTo("0,0")`
`teleportTo("crowd")`
`teleportTo("magic")`

<img width="292" alt="Screen Shot 2020-06-09 at 19 24 35" src="https://user-images.githubusercontent.com/4195708/84212591-a480af00-aa94-11ea-941b-e976ca152342.png">

2020-06-10 12:56 UTC, moliva approved these changes
Amazing! 👏

2020-06-10 12:56 UTC, moliva commented on unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/TeleportPromptHUD/TeleportPromptHUDView.cs
> +                Hide();
Should this `Hide()` be done in any case?

2020-06-10 13:24 UTC, pbosio commented on unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/TeleportPromptHUD/TeleportPromptHUDView.cs
> +                Hide();
The `Hide()` there is in case the command isn't valid (not "crowd", "magic" or valid "x,y" format coords) otherwise `Hide()` is called when pressing any of the popup buttons.
I realize I forgot to log an error there :)

2020-06-10 14:44 UTC, BrianAmadori requested changes

2020-06-10 14:44 UTC, BrianAmadori commented on unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/HUDController.cs
> +        (GetHUDElement(HUDElementID.TELEPORT_DIALOG) as TeleportPromptHUDController)?.RequestTeleport(destination);
In this class, we have the `hud<name>` style getters to save this casting expression. We can replace the casting by adding one of them for the teleport dialog.

2020-06-10 14:44 UTC, BrianAmadori commented on unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/TeleportPromptHUD/TeleportPromptHUDView.cs
> +    const string MARKETPLACE_PARCEL_API = "https://api.decentraland.org/v1/parcels/{0}/{1}";
This info should be controller side

2020-06-10 14:44 UTC, BrianAmadori commented on unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/TeleportPromptHUD/TeleportPromptHUDView.cs
> +        switch (teleportCommand)
This logic sounds like it should be controller side as well. The view shouldn't have any business logic, in any case it should be handled using events.

2020-06-10 14:44 UTC, BrianAmadori commented on unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/TeleportPromptHUD/TeleportPromptHUDView.cs
> +        fetchParcelDataRoutine = StartCoroutine(FetchSceneInfo(coords, (info) =>
Same as above, view should be raising events and controller should be doing this logic.

2020-06-10 14:44 UTC, BrianAmadori commented on unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/TeleportPromptHUD/TeleportPromptHUDView.cs
> +    private void Teleport()
This should be controller side

2020-06-10 14:44 UTC, BrianAmadori commented on unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/TeleportPromptHUD/TeleportPromptHUDView.cs
> +    IEnumerator FetchSceneInfoFallbackMarketPlace(Vector2Int coords)
All of these `Fetch` events sound like they should belong to an static Utils class or controller.

2020-06-10 14:44 UTC, BrianAmadori commented on unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/TeleportPromptHUD/TeleportPromptHUDView.cs
> +    class SceneInfo
All these class definitions should be in another file (controller maybe?).

Usually kernel handles the scene requests heavylifting, I think all of the scene fetching code of this class should be done in the atlas saga and be passed around to this controller. Otherwise we'll breaking patterns here and the code will be less maintainable.

Heads-up to @moliva about this.

2020-06-10 14:44 UTC, BrianAmadori commented on unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/TeleportPromptHUD/TeleportPromptHUDView.cs
> +        content.SetActive(true);
Instead of hiding/showing windows using this, please seriously consider using the `ShowHideAnimator` class so we'd start having show/hide animations support out of the box on all new UI elements.

2020-06-16 18:16 UTC, BrianAmadori approved these changes
looks way better now, awesome work!

2020-06-16 18:16 UTC, BrianAmadori commented on unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/TeleportPromptHUD/TeleportPromptHUDView.cs
> +        if (!string.IsNullOrEmpty(previewImageUrl))
This if can be inverted to reduce nesting

2020-06-16 18:16 UTC, BrianAmadori commented on unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/TeleportPromptHUD/TeleportPromptHUDController.cs
> +        if (!view.contentAnimator.isVisible)
This if can be inverted to reduce nesting

2020-06-16 19:35 UTC, merged