feat: explore -part1- fetch hotscenes
decentraland/explorer pull request #1136
Opened 2020-07-23 20:55 UTC by pbosio

*fetch scenes across realms with people in it
*added hidden chat command to show the first 5 scenes with people in it (helpful for debugging porpoises and meeting new people :P)

2020-07-24 13:05 UTC, moliva requested changes

2020-07-24 13:05 UTC, moliva commented on kernel/packages/shared/social/hotScenes.ts
> +  const tiles = candidate.layer.usersParcels?.map((value) => `${value[0] | 0},${value[1] | 0}`) ?? []
If `usersParcels` is populated, its values ought to be properly initialized. If still, we want to catch any issue with them I would filter out the parcel before taking it into account, as we don't actually know the proper coordinate.

2020-07-24 13:05 UTC, moliva commented on kernel/packages/shared/social/hotScenes.ts
> +      land = (await fetchSceneJson([id]))[0]
Might prove better to fetch both ids and data for the whole set of tiles before iterating though the collection.

2020-07-27 12:51 UTC, moliva approved these changes
Great work! 😄

2020-07-28 15:03 UTC, pablitar approved these changes
LGTM!

2020-07-28 15:55 UTC, merged