Collectibles tab + tests
decentraland/explorer pull request #118
Opened 2019-11-20 16:35 UTC by AjimenezDCL

#50 
Add a new tab where all the collectibles can be found regarding the category.

Amongst the tests for this feature a couple of additional coverage tests for the view has been added.

2019-11-20 16:39 UTC, javiermaria commented on unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/AvatarEditorHUD/Tests/AvatarEditorHUDViewShould.cs
> +            Assert.IsFalse(controller.myView.collectiblesItemSelector.itemToggles.ContainsKey(wearableId));
I think this test is missing something.

2019-11-20 16:41 UTC, AjimenezDCL commented on unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/AvatarEditorHUD/Tests/AvatarEditorHUDViewShould.cs
> +            Assert.IsFalse(controller.myView.collectiblesItemSelector.itemToggles.ContainsKey(wearableId));
No, the `SetUp` method will create everything and the only assertion needed in that test is that no base wearable is in the collectibles list.

It looks okay to me.

2019-11-20 16:41 UTC, javiermaria commented on unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/AvatarEditorHUD/Tests/AvatarEditorHUDViewShould.cs
> +            Assert.IsFalse(controller.myView.collectiblesItemSelector.itemToggles.ContainsKey(wearableId));
-.-

2019-11-21 17:29 UTC, pravusjif commented on unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/AvatarEditorHUD/Scripts/AvatarEditorHUDView.cs
> +        collectiblesItemSelector.OnItemClicked += controller.WearableClicked;
Not sure about this, but shouldn't we unregister all of these events in `Cleanup()` ?

2019-11-21 17:30 UTC, AjimenezDCL commented on unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/AvatarEditorHUD/Scripts/AvatarEditorHUDView.cs
> +        collectiblesItemSelector.OnItemClicked += controller.WearableClicked;
Technically is not needed, because those items are inside the hierarchy of the View and will get destroyed anyway. But its a good practice, will add it =D

2019-11-21 17:31 UTC, pravusjif approved these changes

2019-11-21 17:54 UTC, pravusjif requested changes
Collectibles are not being loaded

2019-11-21 18:35 UTC, pravusjif approved these changes
The collectibles loading problem seems to happen when not using the `&ENV=org` environment

2019-11-21 22:20 UTC, BrianAmadori commented on unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/AvatarEditorHUD/Tests/AvatarEditorHUDViewShould.cs
> +        [TestCase("dcl://base-avatars/f_african_leggins", WearableLiterals.BodyShapes.FEMALE)]
This looks pretty cool, how does it work? It generates a single test for each `TestCase`?

2019-11-22 08:23 UTC, AjimenezDCL commented on unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/AvatarEditorHUD/Tests/AvatarEditorHUDViewShould.cs
> +        [TestCase("dcl://base-avatars/f_african_leggins", WearableLiterals.BodyShapes.FEMALE)]
Yes, exactly. It looks like this in the editor.

![image](https://user-images.githubusercontent.com/50231608/69409633-a312b380-0d09-11ea-825f-2599cdef24f9.png)

2019-11-25 20:00 UTC, BrianAmadori approved these changes

2019-11-26 09:28 UTC, javiermaria commented on unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/AvatarEditorHUD/Scripts/AvatarEditorHUDController.cs
> +        view.AddWearable(wearable, !wearable.tags.Contains("base-wearable"));
To prevent duplicated code, I'd create the Wearable.IsCollectible function where this tag check is performed.
Also, `"base-wearable"` is an excellent candidate for WearableLiterals

2019-11-26 09:29 UTC, javiermaria commented on unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/AvatarEditorHUD/Scripts/AvatarEditorHUDController.cs
> +        view.RemoveWearable(wearable, !wearable.tags.Contains("base-wearable"));
See above

2019-11-26 11:26 UTC, javiermaria approved these changes

2019-11-26 12:27 UTC, merged