feat: gltf to asset bundle batch tool
decentraland/explorer pull request #121
Opened 2019-11-21 17:35 UTC by BrianAmadori

Batch tool parameters quick guide:

`-alwaysBuild`
Build asset bundles regardless of they presence in the content server

`-keepBundles`
Keep downloaded assets in Assets/_Downloaded folder after finished building,
useful for taking advantage of local caching when building many scenes in a row

`-sceneCid <scene-id>`
Download scene with cid

`-parcelsXYWH <x> <y> <width> <height>`
Build all scenes in range of parcels in the rectangle defined.
The rectangle pivot is bottom-left. i.e. 10,10,5,5 will stretch from 10,10 to 15,15.

2019-11-22 09:14 UTC, AjimenezDCL requested changes

2019-11-22 09:14 UTC, AjimenezDCL commented on unity-client/Assets/Batch/AssetBundleMenuItems.cs
> +using UnityEditor;
I see this file is not inside a folder `Editor` is neither having a preprocessing direcitve.  Is a `Batch` folder excluded from builds as well?

2019-11-22 09:14 UTC, AjimenezDCL commented on unity-client/Assets/Batch/Tests/ParseOptionShould.cs
> +    }
I think this is a good opportunity to use the `[TestCase]` attribute and merge them all in a single method.

If you are afraid of losing some semantic in the way due to the automatically generated name of the test you can do something like this:
```
        [UnityTest]
        [TestCase("a", "b", TestName = "Testing_A_B")]
        [TestCase("a", "b", "c")]
        public void ParametrizedTest(params string[] params) {
       }
```
It supports the keyword `params` and you can set the property `TestName` to override the name of the test in the TestRunner. That code would create two test one called `ParametrizedTest("a", "b", "c")` and another one called `Testing_A_B`.

2019-11-22 09:14 UTC, AjimenezDCL commented on unity-client/Assets/Batch/Tests/UtilsTests.cs
> +        }
What is the point of this output? Shouldn't the result of the test in the `.xml` autogenerated file for Tests be enough. Are we gonna run this in an environment where is hard to retrieve files and easier to check the standard output?

2019-11-22 09:14 UTC, AjimenezDCL commented on unity-client/Assets/Scripts/MainScripts/DCL/Helpers/Utils/ContentServerUtils.cs
> +    public static class ContentServerUtils
Are we gonna ever use this for something else than AssetBundles? If no, should we move it to a path within the AssetBundle related scripts?

2019-11-22 09:14 UTC, AjimenezDCL commented on unity-client/Assets/Scripts/MainScripts/DCL/Helpers/Utils/ContentServerUtils.cs
> +        public class MappingPair
I think we should move `MappingPair` to the standard `Utils` collection script. We are using it across the whole project in quite different contexts.

I do agree with taking it out of `ContentProvider` though.

2019-11-25 15:02 UTC, pravusjif commented on unity-client/Assets/Batch/AssetBundleBuilder.cs
> +                t2d = AssetDatabase.LoadAssetAtPath<Texture2D>(outputPath);
Can we assume this texture we are loading is being disposed automatically? or it doesn't matter much because this runs on the content server or similar to transform the assets?

2019-11-25 18:39 UTC, pravusjif approved these changes

2019-11-26 09:45 UTC, javiermaria commented on unity-client/Assets/Batch/AssetBundleBuilder.cs
> +                    if (!GLTFImporter.finishedImporting || Time.realtimeSinceStartup - timer > 60)
Is 60 seconds arbitrary or how did you get to that number? It is reasonable, but I am curious

2019-12-02 21:07 UTC, BrianAmadori commented on unity-client/Assets/Batch/AssetBundleMenuItems.cs
> +using UnityEditor;
Check the `.asmdef` file. The only enabled platform is `Editor`.

2019-12-02 21:08 UTC, BrianAmadori commented on unity-client/Assets/Scripts/MainScripts/DCL/Helpers/Utils/ContentServerUtils.cs
> +        public class MappingPair
The `MappingPair` struct is directly related to the `ContentServer`. That's the reason for being here and not in `Utils`.

2019-12-02 21:10 UTC, BrianAmadori commented on unity-client/Assets/Batch/AssetBundleBuilder.cs
> +                t2d = AssetDatabase.LoadAssetAtPath<Texture2D>(outputPath);
I believe the texture we are loading here is the `AssetDatabase` asset. This means we shouldn't have to `Destroy` it as we'd deleting the texture in that case, like with prefabs.

2019-12-02 21:12 UTC, BrianAmadori commented on unity-client/Assets/Batch/AssetBundleBuilder.cs
> +                    if (!GLTFImporter.finishedImporting || Time.realtimeSinceStartup - timer > 60)
It's just a bailout number in the weird case the `GLTFImporter` got dangling callbacks and `finishedImporting` never reaches true. In all cases I tested it this was never reached, but I'd want to prevent an infinite loop in the case a bug breaks this logic.

2019-12-02 21:17 UTC, BrianAmadori commented on unity-client/Assets/Scripts/MainScripts/DCL/Helpers/Utils/ContentServerUtils.cs
> +    public static class ContentServerUtils
The DCL content server is a very important service that's more or less used by all the client stuff. So, I figured i'd be more useful to have it in the project as a uncoupled system, rather than couple it with the converter logic. This is making sense?

2019-12-03 08:10 UTC, AjimenezDCL commented on unity-client/Assets/Batch/AssetBundleMenuItems.cs
> +using UnityEditor;
Oh, that's really convenient.

2019-12-03 08:16 UTC, AjimenezDCL commented on unity-client/Assets/Scripts/MainScripts/DCL/Helpers/Utils/ContentServerUtils.cs
> +    public static class ContentServerUtils
I was refering to classes like `ScenesAPIData` or `MappingsAPIData`. If I recall correctly, when I wrote that comment the only reference I could found to them was within the AssetBundles ecosystem. Therefore my next comment talking about moving the `MappingPair` to something more common.

Anyway, makes completely sense what you are saying. If those classes are thightly related I understand them being together.

2019-12-03 09:03 UTC, javiermaria approved these changes

2019-12-05 04:42 UTC, eordano commented
Please fix conflicts & merge!

2019-12-05 18:58 UTC, BrianAmadori commented on unity-client/Assets/Batch/Tests/UtilsTests.cs
> +        }
I added this way before because I couldn't make this method run as a test. Removed it.

2019-12-06 14:58 UTC, AjimenezDCL approved these changes

2019-12-06 15:51 UTC, oOZakMcKrackeNOo commented on unity-client/Assets/UnityGLTF/Scripts/GLTFSceneImporter.cs
>                          // var targetCount = primitives[0].Targets.Count;
We should remove commented code.

2019-12-06 15:55 UTC, oOZakMcKrackeNOo approved these changes

2019-12-06 16:30 UTC, pravusjif approved these changes

2019-12-06 18:09 UTC, merged