fix: entites out of boundaries material on remove
decentraland/explorer pull request #1223
Opened 2020-08-27 19:29 UTC by pbosio

In some cases, using debug (preview or builder), if a mesh is removed while out of boundaries it may stay cached with the red "out of boundaries" material instead of it original one.
steps:
* position a mesh outside the scene
* remove that entity from the engine
* add a new entity that uses that glb inside the scene
* red "out of boundaries" material can be observed even if entity is inside the boundaries

2020-08-28 09:26 UTC, sandrade-dcl approved these changes

2020-08-28 22:15 UTC, BrianAmadori requested changes
Cool! We should add test to cover this use case and its good to go.

2020-08-28 22:56 UTC, pbosio commented
> Cool! We should add test to cover this use case and its good to go.

I've tried to create a test for that already, but I couldn't reproduce the issue with the test 🤷‍♂️

2020-08-31 12:29 UTC, pravusjif approved these changes

2020-09-09 13:52 UTC, sandrade-dcl approved these changes

2020-09-09 14:23 UTC, pravusjif approved these changes

2020-09-09 16:46 UTC, BrianAmadori approved these changes

2020-09-09 18:02 UTC, merged