fix: upside down nftshapes
decentraland/explorer pull request #1231
Opened 2020-08-31 12:45 UTC by pravusjif

Re-applied Z rotation to classic NFTShape prefab to fix upside-down picture frames

2020-08-31 13:29 UTC, sandrade-dcl approved these changes

2020-08-31 14:15 UTC, pbosio approved these changes

2020-08-31 16:07 UTC, BrianAmadori requested changes
Can we please add a small test to ensure the rotation is correctly applied and we don't stumble with this regression again?

2020-09-01 20:05 UTC, BrianAmadori approved these changes
Tests added but were marked as explicit because they fail on CI for unknown reason. We have to upload visual tests to CI in order to debug this.

2020-09-01 21:14 UTC, merged