Bones in SkinnedMeshRenderer now are commanded by a mock SkinnedMeshR…
decentraland/explorer pull request #1284
Opened 2020-09-10 16:24 UTC by AjimenezDCL

A disabled SkinnedMeshRenderer will stop moving bones in animations. All the SkinnedMeshRenderer in a character (wearables included) are pinting its bones to the ones in the Head but if we disabled it due a wearable, the whole character will stop animating.

We solved it by creating a mock (no mesh) skinnedmeshrenderer that will act as a director for the bones and never gets disabled.

2020-09-10 16:35 UTC, sandrade-dcl approved these changes

2020-09-10 16:47 UTC, BrianAmadori approved these changes

2020-09-10 16:49 UTC, BrianAmadori requested changes
If i change sex back and forth it get stucks loading.

2020-09-11 12:15 UTC, pravusjif approved these changes
Worked great, damn those skeleton wearables are super cool

2020-09-11 12:58 UTC, sandrade-dcl approved these changes

2020-09-11 14:06 UTC, merged