fix: scene metrics calculations
decentraland/explorer pull request #129
Opened 2019-11-22 18:27 UTC by pbosio

Metrics were not being calculated correctly.

2019-11-22 20:18 UTC, pravusjif approved these changes

2019-11-25 19:01 UTC, BrianAmadori requested changes

2019-11-25 19:01 UTC, BrianAmadori commented on unity-client/Assets/Scripts/MainScripts/DCL/Controllers/Scene/Tests/SceneTests.cs
>              yield return new WaitForSeconds(0.1f);
Why is this statement twice here? Maybe we should remove it.

2019-11-25 19:01 UTC, BrianAmadori commented on unity-client/Assets/Scripts/MainScripts/DCL/Controllers/Scene/Tests/SceneTests.cs
>          public IEnumerator PerformanceLimitControllerTests()
I think we are lacking some support + tests regarding `ParametrizedShape` edge cases. Remember they can switch meshes around without passing through the standard `MeshesInfo` flow (the `ParametrizedShape.UpdateRenderer` lines I showed you the other day)

2019-11-26 09:22 UTC, javiermaria approved these changes

2019-11-26 18:42 UTC, pravusjif approved these changes

2019-11-26 20:33 UTC, BrianAmadori approved these changes

2019-11-26 20:34 UTC, merged