feat: halloween empty parcels
decentraland/explorer pull request #1395
Opened 2020-10-07 00:42 UTC by BrianAmadori

# What? 
...

# Why? 
...

2020-10-07 21:48 UTC, BrianAmadori commented on kernel/packages/shared/meta/sagas.ts
> +    config.world.renderProfile = HALLOWEEN ? RenderProfile.HALLOWEEN : RenderProfile.DEFAULT
Wanted to use the spread operator here with no avail

2020-10-07 21:48 UTC, BrianAmadori commented on kernel/static/loader/empty-scenes-halloween/contents/EP_01.js
> +
These bunch of scenes are exactly the same as the original empty parcels. The only real changes are in the main GLB files.

2020-10-07 21:48 UTC, BrianAmadori commented on kernel/static/loader/empty-scenes-halloween/index.json
> +      "hash": "QmHalloweenEmptyParcels"
As you can see, the Qm hashes are fruta. We should get the proper hashes before submitting those assets to content server/asset bundles s3.

2020-10-08 12:12 UTC, AjimenezDCL reviewed
I see as changes part of the code that was approved here: #1394 I will wait until the branch is rebased into `master` to continue the review.

2020-10-08 12:12 UTC, AjimenezDCL commented on unity-client/Assets/Rendering/Profiles/RenderProfileAvatar.cs
> +        [FormerlySerializedAs("avatarEditorProfile")] [SerializeField]
Once the asset is reimported the `FormerlySerializedAs` can be removed.

2020-10-08 13:54 UTC, BrianAmadori commented
@AjimenezDCL the dependent PR was already merged to `feat/halloween-2020` yesterday.

2020-10-08 13:58 UTC, AjimenezDCL commented
> the dependent PR was already merged to `feat/halloween-2020` yesterday.

Yeah I dont really understand why these files are showing in the `Changes`, it might be related to this PR still having `feat/halloween-2020` as base

2020-10-08 15:01 UTC, sandrade-dcl requested changes
Everything looks fine! Only a few things about to documentation and make our classes clearer.

2020-10-08 15:01 UTC, sandrade-dcl commented on kernel/packages/shared/meta/types.ts
> +  motd?: MotdConfig
What is "motd" meaning? Maybe we should use more descriptive names for this kind of variables/classes (or add some description to the related class).

2020-10-08 15:01 UTC, sandrade-dcl commented on unity-client/Assets/Rendering/Profiles/RenderProfileManifest.cs
> +    public class RenderProfileManifest : ScriptableObject
Following the good practices we agreed, it would be very useful to add some general description to all the new classes we create. Although this is a AssetMenu class, it would be useful to have a basic documentation.

2020-10-08 15:01 UTC, sandrade-dcl commented on unity-client/Assets/Scripts/MainScripts/DCL/Controllers/RenderProfileBridge/RenderProfileBridge.cs
> +public class RenderProfileBridge : MonoBehaviour
The same that I said before about documentate the new classes and public methods :)

2020-10-08 15:39 UTC, BrianAmadori commented on kernel/packages/shared/meta/types.ts
> +  motd?: MotdConfig
It means message of the day. Maybe we can be more verbose with this one. Thanks for the feedback 👍

2020-10-08 15:41 UTC, BrianAmadori commented on unity-client/Assets/Rendering/Profiles/RenderProfileManifest.cs
> +    public class RenderProfileManifest : ScriptableObject
Yep. Good catch 🙂

2020-10-08 18:37 UTC, sandrade-dcl approved these changes

2020-10-08 19:11 UTC, caminoezequiel approved these changes

2020-10-08 20:16 UTC, pravusjif approved these changes

2020-10-08 21:59 UTC, BrianAmadori commented
test

2020-10-08 22:04 UTC, BrianAmadori commented
test

2020-10-08 22:12 UTC, BrianAmadori commented
test

2020-10-09 23:35 UTC, merged