feat: uv multichannel support
decentraland/explorer pull request #1405
Opened 2020-10-08 09:57 UTC by AjimenezDCL

#1390 
UV multichannel support for GLTF. 

Due to the limited amout of TEXCOORDS and given that our shader/Unity use most of them we are facing some limitations. Currently we support 2 UV channels for the Albedo, Normal, Metallic and Emisive maps. Any other texture (Alpha Texture or Ambient Oclussion) will fallback to the UV selected by the Albedo.

We could increase the ammount of channels to 4 or 6 if the need arises but giving support to more textures is going to be tricky.

2020-10-08 09:59 UTC, AjimenezDCL commented
WARNING (mostly for my future self).

This feature is branching from PR: #1388 to avoid conflicts since both PRs modify the similar parts of the code. So once said PR is merged into master, we can change the base branch on this PR to `master` and process as normal.

2020-10-08 12:13 UTC, pravusjif requested changes
![Screen Shot 2020-10-08 at 09 11 55](https://user-images.githubusercontent.com/1031741/95456885-6ada8a80-0946-11eb-9987-9252720559df.png)

There seems to be a bug affecting materials/textures

2020-10-08 13:48 UTC, pravusjif approved these changes

2020-10-09 09:16 UTC, sandrade-dcl approved these changes

2020-10-09 13:00 UTC, BrianAmadori commented on unity-client/Assets/Shaders/MaterialTransition/LWRP/LitForwardPass.hlsl
> +    output.uvMetallicEmissive.zw = uvs[clamp(_EmissiveMapUVs, 0, 1)];
we can't use `saturate` instead of `clamp` here?

2020-10-09 13:32 UTC, AjimenezDCL commented on unity-client/Assets/Shaders/MaterialTransition/LWRP/LitForwardPass.hlsl
> +    output.uvMetallicEmissive.zw = uvs[clamp(_EmissiveMapUVs, 0, 1)];
Isn't it the same? I thought `clamp` is just a wrap around `saturate`. We can use `saturate` if you like it more

2020-10-09 15:09 UTC, BrianAmadori commented on unity-client/Assets/Shaders/MaterialTransition/LWRP/LitForwardPass.hlsl
> +    output.uvMetallicEmissive.zw = uvs[clamp(_EmissiveMapUVs, 0, 1)];
I think `saturate` is more succinct. It's also supposed to be heavily optimized to deal with the 0,1 case.

2020-10-09 15:11 UTC, AjimenezDCL commented on unity-client/Assets/Shaders/MaterialTransition/LWRP/LitForwardPass.hlsl
> +    output.uvMetallicEmissive.zw = uvs[clamp(_EmissiveMapUVs, 0, 1)];
Fair enough, on it!

2020-10-09 16:00 UTC, BrianAmadori approved these changes
Looks good!

2020-10-09 16:28 UTC, merged