feat: layered sky shader
decentraland/explorer pull request #1445
Opened 2020-10-15 23:57 UTC by BrianAmadori

2020-10-16 10:55 UTC, AjimenezDCL approved these changes

2020-10-16 14:05 UTC, pravusjif requested changes
In this PR, the normal (not halloween) sky got f*cked up, the texture looks all stretched and has weird cuts

![Screen Shot 2020-10-16 at 11 04 27](https://user-images.githubusercontent.com/1031741/96268468-7c074500-0f9f-11eb-92ae-9ecf72bd029d.png)

![Screen Shot 2020-10-16 at 11 04 32](https://user-images.githubusercontent.com/1031741/96268482-80336280-0f9f-11eb-8785-418d5196c939.png)

2020-10-20 11:51 UTC, sandrade-dcl approved these changes

2020-10-20 14:02 UTC, pravusjif approved these changes

2020-10-21 21:14 UTC, merged