fix: unity builder fixes, loading and selection improvements
decentraland/explorer pull request #157
Opened 2019-11-27 18:51 UTC by pbosio

What?

* fix: scenes unloading. Receive keyboard input from builder instead of using Unity's
* refactor: entities selection, dragging and gizmos
* fix: gltf prefetch
* fix: outline for selected entities
* fix: z-fighting in editor mode
* fix: receive camera rotation and position from builder in preview mode

2019-11-29 20:10 UTC, pravusjif approved these changes

2019-12-02 17:17 UTC, BrianAmadori requested changes
On top of those requests, we need tests for:

- The prefetch GLTF promise
- Gizmos
- DCLBuilderGizmoManager
- DCLBuilderMeshLoadIndicatorController

2019-12-02 17:17 UTC, BrianAmadori commented on unity-client/Assets/Builder/Scripts/DCLBuilderEntity.cs
> +                    if (rootEntity.meshesInfo.renderers[i])
This expression can be a bit more readable if we move the `Renderer` instance to a new local variable.

2019-12-02 17:17 UTC, BrianAmadori commented on unity-client/Assets/Builder/Scripts/DCLBuilderEntity.cs
> +        private Action onShapeLoaded;
```suggestion
        private Action OnShapeLoaded;
```

2019-12-02 17:17 UTC, BrianAmadori commented on unity-client/Assets/Builder/Scripts/DCLBuilderOutline.cs
> +            outlineRawImage.transform.localScale = Vector3.one;
If you import `Utils` you have the extension method `Transform.ResetLocalTRS` to do this.

2019-12-02 17:17 UTC, BrianAmadori commented on unity-client/Assets/Builder/Scripts/DCLBuilderSelectionCollider.cs
> +            Utils.ResetLocalTRS(t);
```suggestion
            t.ResetLocalTRS();
```

2019-12-02 17:17 UTC, BrianAmadori commented on unity-client/Assets/Builder/Scripts/Gizmos/DCLBuilderGizmoManager.cs
> +                if (IsGizmoShowing() && activeGizmo.GetGizmoType() != gizmoType)
Maybe we can add all those checks and `activeGizmo = null` inside `HideGizmo`. So this method is a bit easier to read.

2019-12-02 17:17 UTC, BrianAmadori commented on unity-client/Assets/Builder/Scripts/Gizmos/DCLBuilderRotateGizmo.cs
> +            float enter = 0.0f;
This `enter` name is a bit obscure. What i'm supossed to infer by it?

2019-12-02 17:17 UTC, BrianAmadori commented on unity-client/Assets/Scripts/MainScripts/Debugging/WSS/WSSController.cs
> +                            case "BuilderReady":
I have a concern with this message structure because its not homogeneous with the rest of our architecture. We should use a single message and enum types to infer the action type.

2019-12-09 18:22 UTC, BrianAmadori commented on unity-client/Assets/Scripts/MainScripts/Debugging/WSS/WSSController.cs
> +                            case "BuilderReady":
We'll move this to another issue.

2019-12-09 18:22 UTC, BrianAmadori commented on unity-client/Assets/Builder/Scripts/Gizmos/DCLBuilderGizmoManager.cs
> +                if (IsGizmoShowing() && activeGizmo.GetGizmoType() != gizmoType)
@pbosio is going to redesign this code and solve this issue in a future PR, closing this.

2019-12-09 20:25 UTC, BrianAmadori approved these changes

2019-12-09 20:46 UTC, merged