fix: video player reset
decentraland/explorer pull request #1685
Opened 2020-11-23 12:07 UTC by pravusjif

WHY?
the documentation on the video player at https://docs.decentraland.org/development-guide/video-playing/ states that the `reset()` method should stop the video. We are not doing this and so there is undesired behaviour like playing audio from a previous video as stated in #1622 

WHAT?
removed playing the video when resetting and the bug is fixed.

2020-11-23 12:34 UTC, AjimenezDCL approved these changes

2020-11-23 15:36 UTC, sandrade-dcl approved these changes

2020-11-23 18:42 UTC, pbosio commented
I think this should be done from the component and not from the jslib
`packages/decentraland-ecs/src/decentraland/Components.ts` (L:1052)
```
  reset() {
    this.seekTime(0)
    + this.playing = false
  }
```
and probably change the order at `Assets/Scripts/MainScripts/DCL/Components/Video/DCLVideoTexture.cs`
to make sure that `model.seek` field is checked before `model.playing`
cause I don't know if we want component's `seekTime` method to stop the video also and that will happen with the approach used in ths PR

2020-11-23 18:47 UTC, pbosio requested changes
comment leaved before :P

2020-11-24 21:40 UTC, pbosio approved these changes
LGTM

2020-11-24 23:41 UTC, merged