feat: input controller system
decentraland/explorer pull request #169
Opened 2019-11-29 15:38 UTC by AjimenezDCL

New Input Controller which allows us to decouple CharacterController, CameraController and how the inputs are received.

It also contains the very raw implementation of a multicamera system. Once the system get's the approval we "just" have to tweak cinemachine virtual cameras.

2019-11-29 16:43 UTC, BrianAmadori commented on unity-client/Assets/Scripts/MainScripts/DCL/Controllers/InputController/InputActionResolverFactory.cs
> +    internal static InputActionResolver_OneTime[] CreateInstance(InputAction_OneTime oneTimeAction)
Why are we returning an array here? In which cases we would need more than one resolver?

2019-11-29 16:43 UTC, BrianAmadori commented on unity-client/Assets/Scripts/MainScripts/DCL/Controllers/InputController/InputAction_InTime.cs
> +    private void CleanUp()
Maybe we can move this code to a base class?

2019-11-29 16:43 UTC, BrianAmadori commented on unity-client/Assets/Scripts/MainScripts/DCL/Controllers/InputController/InputAction_Measurable.cs
> +internal class MouseButtonInputActionResolver_Measurable : InputActionResolver_Measurable
All of the input specific stuff shouldn't be in the InputController layer? I imagined the base measurable was going to listen to an input BaseVariable instead of this.

2019-11-29 16:46 UTC, AjimenezDCL commented on unity-client/Assets/Scripts/MainScripts/DCL/Controllers/InputController/InputActionResolverFactory.cs
> +    internal static InputActionResolver_OneTime[] CreateInstance(InputAction_OneTime oneTimeAction)
We can have multiple resolvers mapped to the same Action. Like MainAction with LeftMouseButton and E in the keyboard. It's also a pre-step to allow multiple devices at the same time, like controllers + keyboard (if im not mistaken you can use controllers in WebGL)

2019-11-29 16:47 UTC, AjimenezDCL commented on unity-client/Assets/Scripts/MainScripts/DCL/Controllers/InputController/InputAction_InTime.cs
> +    private void CleanUp()
I created a base class and deleted it. Besides the cleanup (only for Editor) I cannot really get common functionality since I cannot make Resolvers to inheritance a base class

2019-11-29 17:04 UTC, AjimenezDCL commented on unity-client/Assets/Scripts/MainScripts/DCL/Controllers/InputController/InputAction_Measurable.cs
> +internal class MouseButtonInputActionResolver_Measurable : InputActionResolver_Measurable
Could you sketch how would it look?

2019-12-01 19:13 UTC, AjimenezDCL commented on unity-client/Assets/Scripts/MainScripts/DCL/Controllers/InputController/InputAction_Measurable.cs
> +internal class MouseButtonInputActionResolver_Measurable : InputActionResolver_Measurable
I think now I understand what you meant. Basically remove the Resolvers and move that logic to the InputController right? After giving it some thoughts in the weekend I think it could lead to a really elegant solution. Gonna change it on Monday and let's see how it looks

Although I see redundant what you said about an Action listening to another BaseVariable. 
What I'm gonna do is:
- InputController update Actions (each Action is a SO).
- Actions raise events when updated: 
    - OneTimeAction: OnTriggered
    - InTimeAction: OnStarted, OnFinished
    - MeasurableAction: OnValueChanged
- Systems in the project will suscribe to those Actions, for example:
   - DCLCharacterController will listen to an OneTimeAction.OnTriggered called Jump 
   - DCLCharacterController will listen to an InTimeAction.OnStarted and OnFinished called Sprint

I dont see where those extra BaseVariable you mentioned would go.

2019-12-02 15:53 UTC, BrianAmadori commented on unity-client/Assets/Scripts/MainScripts/DCL/Controllers/InputController/InputAction_Measurable.cs
> +internal class MouseButtonInputActionResolver_Measurable : InputActionResolver_Measurable
I think when I was referring to `BaseVariable` i was actually referring to Actions. I picture the `InputController` updating `Actions` and handling the keybinding to the different devices. Then, the other systems suscribe to those actions in order listen to the input.

2019-12-02 18:30 UTC, AjimenezDCL commented on unity-client/Assets/Scripts/MainScripts/DCL/Controllers/InputController/InputAction_Measurable.cs
> +internal class MouseButtonInputActionResolver_Measurable : InputActionResolver_Measurable
So more or less what is currently implemented? I dont really like the `InputProcessor` class but without that `InputController` would contain a lot of boilerplate

2019-12-06 14:51 UTC, BrianAmadori requested changes

2019-12-06 14:51 UTC, BrianAmadori commented on unity-client/Assets/Scripts/MainScripts/DCL/Controllers/Camera/CameraController.cs
> +    [SerializeField] internal InputAction_OneTime cameraChangeAction;
Remember we agreed upon changing the names to:
`InputAction_OneTime` -> `InputAction_Trigger` 
`InputAction_InTime` -> `InputAction_Hold`

2019-12-06 14:51 UTC, BrianAmadori commented on unity-client/Assets/Scripts/MainScripts/DCL/Controllers/Camera/CameraController.cs
> +            switch (currentMode)
The mode specific code shouldn't be inside a `CameraSetup` instead on a switch?

2019-12-06 14:51 UTC, BrianAmadori commented on unity-client/Assets/Scripts/MainScripts/DCL/Controllers/Camera/Tests/CameraTests.cs
> +﻿//using System.Collections;
Remember to remove commented code.

2019-12-06 14:51 UTC, BrianAmadori commented on unity-client/Assets/Scripts/MainScripts/DCL/Controllers/InputController/InputController.cs
> +                case DCLAction_OneTime.Jump:
Ideally i'd try to set those action mappings in a more data-driven fashion. So we can set them modifying an inspector struct array or similar. I have a similar issue with the `InputProcessor` methods. If isn't too difficult to design this part of the system using an strategy pattern I'd give a shot at it.

2019-12-06 14:52 UTC, AjimenezDCL commented on unity-client/Assets/Scripts/MainScripts/DCL/Controllers/Camera/CameraController.cs
> +    [SerializeField] internal InputAction_OneTime cameraChangeAction;
Oopsie, I completely forgot. Gonna change it

2019-12-06 14:55 UTC, AjimenezDCL commented on unity-client/Assets/Scripts/MainScripts/DCL/Controllers/Camera/CameraController.cs
> +            switch (currentMode)
I removed `CameraSetup` becase almost everything done there was overtaken by Cinemachine. I could create those `CameraSetup` and add this code, but it might be overkill.

Dont worry about the document/diagrams. Once the review is done I will update it.

2019-12-06 15:07 UTC, BrianAmadori commented on unity-client/Assets/Scripts/MainScripts/DCL/Controllers/Camera/CameraController.cs
> +            switch (currentMode)
Ok, as we agreed we are going to refactor this in the polish phase if we found it necessary.

2019-12-06 15:10 UTC, BrianAmadori commented on unity-client/Assets/Scripts/MainScripts/DCL/Controllers/InputController/InputController.cs
> +                case DCLAction_OneTime.Jump:
As we agreed, we are going to standby on this change and keep it as technical debt. As we have the following issues:

- We need to map actions to KeyCode / MouseButton / etc. and the required struct can get a bit messy.
- We may be gold plating this as Unity is rolling a new Input system, and we didn't investigate enough to know if it can save us this binding code.

2019-12-06 15:32 UTC, BrianAmadori approved these changes

2019-12-06 15:32 UTC, BrianAmadori commented on unity-client/Assets/Scripts/MainScripts/DCL/Controllers/InputController/InputController.cs
> +    [FormerlySerializedAs("oneTimeActions")] public InputAction_Trigger[] triggerTimeActions;
When the prefab is re-serialized and the values are copied from the old field to the new one you can remove this attribute.

2019-12-06 15:35 UTC, AjimenezDCL commented on unity-client/Assets/Scripts/MainScripts/DCL/Controllers/InputController/InputController.cs
> +    [FormerlySerializedAs("oneTimeActions")] public InputAction_Trigger[] triggerTimeActions;
Oh yes, I was planing to do it but got caught in something else and forgot. Mini commit to fix it

2019-12-06 16:47 UTC, pravusjif commented on unity-client/Assets/Scripts/MainScripts/DCL/Components/Billboard/Billboard.cs
> +            Vector3 lookAtDir = (entityTransform.position - cameraPosition);
This is actually wrong (it was wrong before you updated it, and i fixed it in the tests PR) the calculation should be the other way around: `cameraPosition - entityTransform.position` to get the vector that looks **towards the player**. But, leave it like this and I'll keep the fix when resolving this conflict with the tests fix PR

2019-12-06 17:34 UTC, pravusjif requested changes

2019-12-06 17:34 UTC, pravusjif commented on unity-client/Assets/Scripts/MainScripts/DCL/Controllers/DCLCharacterController.cs
> +            if (Time.time - lastJumpButtonPressedTime < 0.15f) // almost-grounded jump button press allowed time
This is not working correclty, try it out, press the jump button a moment before hitting the ground (keep pressing it) and the chara should start jumping as soon as it hits the ground, it worked before, you can compare with .zone: https://explorer.decentraland.zone/

2019-12-06 17:34 UTC, pravusjif commented on unity-client/Assets/Scripts/MainScripts/DCL/Controllers/DCLCharacterController.cs
> +            if (Time.time - lastJumpButtonPressedTime < 0.15f) // almost-grounded jump button press allowed time
We also lost the "just ungrounded jump" feature

2019-12-09 13:22 UTC, pravusjif approved these changes

2019-12-09 13:45 UTC, merged