chore: unity 2019.4.19f1 update
decentraland/explorer pull request #2096
Opened 2021-02-19 01:38 UTC by BrianAmadori

# What? 
...

# Why? 
...

2021-02-26 09:44 UTC, sandrade-dcl requested changes
I have tested the build and it seems all the audio sfx (for example all the buttons clicks) have been lost. However the ambience sounds (the birds) are working.

2021-02-26 09:44 UTC, sandrade-dcl commented on unity-client/Assets/Scripts/MainScripts/DCL/Controllers/Scene/SceneController.cs
> +
Can we remove this empty line? (I guess it was an oversight)

2021-02-26 09:44 UTC, sandrade-dcl commented on unity-client/Assets/Scripts/MainScripts/DCL/Controllers/Scene/SceneController.cs
> +            //
The same as above.

2021-02-26 10:15 UTC, AjimenezDCL commented
I'm having issues with the sound as well. In any case the rest looks good, I will drop an approve since Santi already requested changes. Good job!

2021-02-26 10:17 UTC, AjimenezDCL approved these changes

2021-03-02 22:01 UTC, pravusjif approved these changes
Tested the build with no problems besides the no-sfx issue

2021-03-03 12:57 UTC, sandrade-dcl approved these changes
Sound SFX fixed!

2021-03-08 17:39 UTC, merged