Feat/biw ux improvements 2
decentraland/explorer pull request #2202
Opened 2021-03-15 09:43 UTC by Suduck

# What

This PR includes some bug fixes, some UX improvements, and unit testing to the builder in world

2021-03-15 12:56 UTC, sandrade-dcl requested changes

2021-03-15 12:56 UTC, sandrade-dcl commented on unity-client/Assets/Scripts/MainScripts/DCL/Controllers/BuilderMode/BuilderEntity/DCLBuilderInWorldEntity.cs
> +        if (meshAnimations == null || meshAnimations.Length <= 0)
As a `Length` (or `Count`) property cannot never be less than 0, I think the using of `== 0` will make the code more understandable than `<= 0`.

```suggestion
        if (meshAnimations == null || meshAnimations.Length == 0)
```

2021-03-15 12:56 UTC, sandrade-dcl commented on unity-client/Assets/Scripts/MainScripts/DCL/Controllers/BuilderMode/BuilderEntity/DCLBuilderInWorldEntity.cs
> +            rootEntity.meshesInfo.renderers.Length < 1)
```suggestion
            rootEntity.meshesInfo.renderers.Length == 0)
```

2021-03-15 12:56 UTC, sandrade-dcl commented on unity-client/Assets/Scripts/MainScripts/DCL/Controllers/BuilderMode/Controllers/BuilderInWorldEntityHandler.cs
> +        if (selectedEntities.Count <= 0)
```suggestion
        if (selectedEntities.Count == 0)
```

2021-03-15 12:56 UTC, sandrade-dcl commented on unity-client/Assets/Scripts/MainScripts/DCL/Controllers/BuilderMode/States/FirstPerson/BuilderInWorldFirstPersonMode.cs
> +        if (selectedEntities.Count <= 0 || isMultiSelectionActive)
```suggestion
        if (selectedEntities.Count == 0 || isMultiSelectionActive)
```

2021-03-15 12:56 UTC, sandrade-dcl commented on unity-client/Assets/Scripts/MainScripts/DCL/Controllers/BuilderMode/States/FirstPerson/BuilderInWorldFirstPersonMode.cs
> +        if (selectedEntities.Count <= 0)
```suggestion
        if (selectedEntities.Count == 0)
```

2021-03-15 16:22 UTC, pravusjif commented on unity-client/Assets/Scripts/MainScripts/DCL/Controllers/BuilderMode/BuilderEntity/DCLBuilderInWorldEntity.cs
> +            return true;
this could be a one liner right?
`return GetCatalogItemAssociated()?.category == BuilderInWorldSettings.FLOOR_CATEGORY;`

2021-03-15 16:27 UTC, pravusjif approved these changes

2021-03-16 09:39 UTC, sandrade-dcl approved these changes

2021-03-16 11:30 UTC, AjimenezDCL approved these changes
Some small comments, good job!

2021-03-16 11:30 UTC, AjimenezDCL commented on unity-client/Assets/Scripts/MainScripts/DCL/Controllers/BuilderMode/Controllers/BIWFloorHandler.cs
> +        Debug.Log("Floor loading timeout " + entityId);
I guess this is just a testing debug that should be removed.

2021-03-16 11:30 UTC, AjimenezDCL commented on unity-client/Assets/Scripts/MainScripts/DCL/Controllers/BuilderMode/States/EditorMode/BuilderInWorldGodMode.cs
> +            HUDController.i.builderInWorldMainHud.ActivateGodModeUI();
You can use the null-conditial operator here:
```suggestion
HUDController.i.builderInWorldMainHud?.ActivateGodModeUI();
```

2021-03-16 12:18 UTC, Suduck commented on unity-client/Assets/Scripts/MainScripts/DCL/Controllers/BuilderMode/Controllers/BIWFloorHandler.cs
> +        Debug.Log("Floor loading timeout " + entityId);
Changed to `LogError`

2021-03-16 12:38 UTC, merged