feat: interaction hover feedback
decentraland/explorer pull request #222
Opened 2019-12-11 21:04 UTC by pravusjif

* Added logic for interactive objects detection (OnClick and OnPointerDown components)
* Added place holder prefab that will be tuned up later by Romi
* Disabled hover feedback until the implementation is finished in the next PR (`PointerEventsController.enableInteractionHoverFeedback`)

2019-12-18 14:37 UTC, BrianAmadori reviewed
`edited`

2019-12-18 14:47 UTC, BrianAmadori requested changes
We should add at least a single test that checks the toast is being displayed as intended.

Also, all the assets related to this feature should be under a feature related folder. Putting everything inside the same root `Resources` folder will become unmanageable in the long run.

2019-12-18 14:47 UTC, BrianAmadori commented on unity-client/Assets/Scripts/MainScripts/DCL/Controllers/InteractionHoverCanvasController.cs
> +        switch (button)
I think we should just use prefabs instead of setting the UI element properties like this. It'd be more manageable and Romi could take care of it without changing code, as we are already doing with the avatar editor stuff.

2019-12-18 14:47 UTC, BrianAmadori commented on unity-client/Assets/Scripts/MainScripts/DCL/Controllers/PointerEventsController.cs
> +                if (RenderingController.i.renderingEnabled)
We can invert this `if` to avoid indentation.

2019-12-18 16:18 UTC, pravusjif commented on unity-client/Assets/Scripts/MainScripts/DCL/Controllers/InteractionHoverCanvasController.cs
> +        switch (button)
OK, but in the future we will probably come back to an approach similar to the current one, when we let the users bind the input to any key

2019-12-18 16:32 UTC, pravusjif commented on unity-client/Assets/Scripts/MainScripts/DCL/Controllers/PointerEventsController.cs
> +                if (RenderingController.i.renderingEnabled)
Done

2019-12-18 17:15 UTC, pravusjif commented on unity-client/Assets/Scripts/MainScripts/DCL/Controllers/InteractionHoverCanvasController.cs
> +        switch (button)
Done, made 4 separate hover icon prefabs (one for each action, including the "unknown" input action as well)

2019-12-18 20:56 UTC, pravusjif commented
> We should add at least a single test that checks the toast is being displayed as intended.
> 
> Also, all the assets related to this feature should be under a feature related folder. Putting everything inside the same root `Resources` folder will become unmanageable in the long run.

Added a test

2019-12-19 15:26 UTC, BrianAmadori requested changes

2019-12-19 15:26 UTC, BrianAmadori commented on unity-client/Assets/Scripts/MainScripts/DCL/Controllers/InteractionHoverCanvas/InteractionHoverCanvasController.cs
> +        hoverIcon = Object.Instantiate(Resources.Load(prefabPath), backgroundTransform) as GameObject;
Why are we using `Resources.Load` here? As this is a `MonoBehaviour`, we could reference the prefabs directly using this prefab serialization. This is better because we don't depend on the object names/path for this to work.

2019-12-19 15:26 UTC, BrianAmadori commented on unity-client/Assets/Scripts/MainScripts/DCL/Controllers/PointerEventsController.cs
>              InputController_Legacy.i.RemoveListener(WebInterface.ACTION_BUTTON.SECONDARY, OnButtonEvent);
We shouldn't kill the coroutine here too?

2019-12-19 15:26 UTC, BrianAmadori commented on unity-client/Assets/Scripts/MainScripts/DCL/Components/UUIDComponent/OnPointerEventComponent.cs
> +    public class OnPointerEventComponent : UUIDComponent<OnPointerEventComponent.Model>
The `Component` name in all those family of classes is redundant. I think the code is a bit more readable if we remove it.
```suggestion
    public class OnPointerEvent : UUIDComponent<OnPointerEvent.Model>
```

2019-12-19 15:26 UTC, BrianAmadori commented on unity-client/Assets/Scripts/MainScripts/DCL/Components/UUIDComponent/OnPointerEventComponent.cs
> +    public class OnPointerEventComponent : UUIDComponent<OnPointerEventComponent.Model>
Just checked and it doesn't seem to produce any name collision. So its safe to rename it.

2019-12-19 15:26 UTC, BrianAmadori commented on unity-client/Assets/Scripts/MainScripts/DCL/Controllers/InteractionHoverCanvas/InteractionHoverCanvasController.cs
> +﻿using UnityEngine;
I think this class and all the resources related to it should be under a subfolder in the `UUIDComponent` subfolder, as its only used by the `PointerEvent` base class.

2019-12-19 16:26 UTC, pravusjif commented on unity-client/Assets/Scripts/MainScripts/DCL/Controllers/InteractionHoverCanvas/InteractionHoverCanvasController.cs
> +        hoverIcon = Object.Instantiate(Resources.Load(prefabPath), backgroundTransform) as GameObject;
OK, let's keep that as a rule then, yesterday I almost ask you how you'd like this instantiation to be made and ended up using the Resources way because we use that everywhere i think, then let's always use referene instantiation in monobehaviours, I'm changing it now.

2019-12-19 16:36 UTC, pravusjif commented on unity-client/Assets/Scripts/MainScripts/DCL/Controllers/InteractionHoverCanvas/InteractionHoverCanvasController.cs
> +        hoverIcon = Object.Instantiate(Resources.Load(prefabPath), backgroundTransform) as GameObject;
done

2019-12-19 16:39 UTC, pravusjif commented on unity-client/Assets/Scripts/MainScripts/DCL/Controllers/PointerEventsController.cs
>              InputController_Legacy.i.RemoveListener(WebInterface.ACTION_BUTTON.SECONDARY, OnButtonEvent);
I don't think so, since there is no persistent data related to this, but I added a little cleanup code (reset the `lastHoveredObject` and `newHoveredObject` vars)

2019-12-19 16:51 UTC, pravusjif commented on unity-client/Assets/Scripts/MainScripts/DCL/Components/UUIDComponent/OnPointerEventComponent.cs
> +    public class OnPointerEventComponent : UUIDComponent<OnPointerEventComponent.Model>
Done

2019-12-19 16:52 UTC, pravusjif commented on unity-client/Assets/Scripts/MainScripts/DCL/Controllers/InteractionHoverCanvas/InteractionHoverCanvasController.cs
> +﻿using UnityEngine;
Done

2019-12-19 16:55 UTC, BrianAmadori commented on unity-client/Assets/Scripts/MainScripts/DCL/Controllers/PointerEventsController.cs
>              InputController_Legacy.i.RemoveListener(WebInterface.ACTION_BUTTON.SECONDARY, OnButtonEvent);
If we don't kill coroutines on Cleanup methods consecutive tests might fail in the cases of not reloading scenes. Remember we are going in that direction now with the test perf. fixes.

2019-12-19 16:59 UTC, pravusjif commented on unity-client/Assets/Scripts/MainScripts/DCL/Controllers/PointerEventsController.cs
>              InputController_Legacy.i.RemoveListener(WebInterface.ACTION_BUTTON.SECONDARY, OnButtonEvent);
The thing is, if the scene is not reloaded, the SceneController doesn't call its Awake, the PointerEventsController.Initialize is not called and this coroutine never starts again, if we want that... then I can add the StopCoroutine, no problem

2019-12-19 17:20 UTC, BrianAmadori approved these changes

2019-12-19 17:20 UTC, BrianAmadori commented on unity-client/Assets/Scripts/MainScripts/DCL/Components/UUIDComponent/OnPointerDownComponent.cs
> +    public class OnPointerDownComponent : OnPointerEvent
We shouldn't be renaming those classes too?

2019-12-19 17:59 UTC, pravusjif commented on unity-client/Assets/Scripts/MainScripts/DCL/Components/UUIDComponent/OnPointerDownComponent.cs
> +    public class OnPointerDownComponent : OnPointerEvent
Yes, you're right, i just renamed OnPointerDownComponent, OnPointerUpComponent and OnClickComponent

2019-12-19 19:08 UTC, pbosio approved these changes

2019-12-19 19:15 UTC, merged