fix: objects blocking OnPointerDown/OnClick events
decentraland/explorer pull request #224
Opened 2019-12-12 14:57 UTC by pbosio

User was able to click stuffs through walls and other objects.

2019-12-12 16:19 UTC, BrianAmadori submitted a review, later dismissed
In addition to the comments, I'd write a test to ensure this keeps working in the future. Looks pretty good overall!.

2019-12-12 16:19 UTC, BrianAmadori commented on unity-client/Assets/Scripts/MainScripts/DCL/Controllers/PointerEventsController.cs
> +                        bool isOnClickComponentBlocked =
This code shouldn't be repeated like this. We can't extract this whole "shouldn't be blocked" logic to a method?

2019-12-12 16:19 UTC, BrianAmadori commented on unity-client/Assets/Scripts/MainScripts/DCL/Controllers/PointerEventsController.cs
> +                            raycastInfoGlobalLayer.hitInfo != null
I'd explain the approach with a mini-wall of text comment too, because the logic is a bit non-obvious.

2019-12-13 08:31 UTC, AjimenezDCL requested changes

2019-12-13 08:31 UTC, AjimenezDCL commented on unity-client/Assets/Scripts/MainScripts/DCL/Controllers/PointerEventsController.cs
> +                        if (!isOnClickComponentBlocked && isSameEntityThatWasPressed)
Isn't `AreCollidersFromSameEntity` called inside `IsBlockingOnClock`?

2019-12-13 14:00 UTC, pbosio commented on unity-client/Assets/Scripts/MainScripts/DCL/Controllers/PointerEventsController.cs
> +                        if (!isOnClickComponentBlocked && isSameEntityThatWasPressed)
Yes, but we are checking different stuffs...
in `bool isOnClickComponentBlocked = IsBlockingOnClick(raycastInfoPointerEventLayer.hitInfo, raycastInfoGlobalLayer.hitInfo);` we are checking if the raycast for the global layer is hitting something that is blocking the hit in the OnPointerEvent layer
and in `bool isSameEntityThatWasPressed = AreCollidersFromSameEntity(raycastInfoPointerEventLayer.hitInfo, lastPointerDownEventHitInfo);` we are making sure that the object we clicked previously is the same as the object we were pointing at when mouse click is released

2019-12-13 14:14 UTC, AjimenezDCL commented on unity-client/Assets/Scripts/MainScripts/DCL/Controllers/PointerEventsController.cs
> +                        if (!isOnClickComponentBlocked && isSameEntityThatWasPressed)
Dammit... I didnt see that the params are different. Sorry!

2019-12-13 14:14 UTC, AjimenezDCL approved these changes

2019-12-13 16:10 UTC, BrianAmadori commented on unity-client/Assets/Scripts/MainScripts/DCL/Controllers/PointerEventsController.cs
> +                            raycastInfoGlobalLayer.hitInfo.hit.point,
I'd extract the `raycastInfoGlobalLayer.hitInfo` to a method scoped variable.

2019-12-13 16:10 UTC, BrianAmadori commented on unity-client/Assets/Scripts/MainScripts/DCL/Controllers/PointerEventsController.cs
> +                            raycastInfoGlobalLayer.hitInfo.hit.normal,
I'd extract the `raycastInfoGlobalLayer.hitInfo` to a method scoped variable.

2019-12-17 16:29 UTC, pravusjif approved these changes

2019-12-17 17:22 UTC, BrianAmadori approved these changes

2019-12-17 17:23 UTC, merged