fix: camera feel polish improvements
decentraland/explorer pull request #227
Opened 2019-12-12 20:47 UTC by BrianAmadori

List of changes related to feel:

* Walk/run speed was _decreased_ to make animations look correctly. Now holding shift key makes character walk instead running. Running is the default movement action.  This also has the side effect of giving more time to the furthest scenes to load.

* Animation jitter fixes. Avatar rotates correctly according to its movement direction. 

* Avatar framing polish according to @RominaMarchetti @ShibuyaMartin @MadRex and myself.

* When strafing the avatar rotates to the left/right, and camera follows (without the mario64 rotation style).

* First draft of camera collision behaviour

* fix: Going to third person after rotating in first person could cause the camera to "remember" the previous rotation angle incorrectly, in a way that third person started looking at the avatar sideways when it shouldn't.

* fix: Avatar was clipping the floor in most cases.

* fix: Avatars lacked shadows.

Known issues:

* Camera jitters when avatar is on top of moving platforms.

* We still have many camera collision issues. Some of them caused by bad collider placement. This known to be a very difficult theme in all games that implement it and will be an ongoing effort.

2019-12-14 15:35 UTC, eordano commented
Please rebase/solve conflicts

2019-12-14 15:37 UTC, eordano approved these changes
All looking good, one minor comment only: please delete commented code

2019-12-14 15:37 UTC, eordano commented on unity-client/Assets/Scripts/MainScripts/DCL/Components/LoadableShapes/LoadWrapper/LoadWrapper_GLTF.cs
> +            //if (useGltfFallback)
No commented code please

2019-12-19 17:31 UTC, pravusjif commented on unity-client/Assets/Scripts/MainScripts/DCL/Controllers/Camera/CameraController.cs
> +    public GameObject cursor;
Where is this being used?

2019-12-19 17:46 UTC, pravusjif requested changes

2019-12-19 17:46 UTC, pravusjif commented on unity-client/Assets/Scripts/MainScripts/DCL/Controllers/Camera/CameraStateFPS.cs
> +    }
This overrides look unnecessary as they only call the same base class method inside

2019-12-19 17:46 UTC, pravusjif commented on unity-client/Assets/Scripts/MainScripts/DCL/Controllers/Camera/CameraStateTPS.cs
> +    }
We could remove this override

2019-12-19 17:53 UTC, BrianAmadori commented on unity-client/Assets/Scripts/MainScripts/DCL/Controllers/Camera/CameraController.cs
> +    public GameObject cursor;
Initially I was hiding the cursor in TPS, but I deleted the code later because its better to hide the cursor when we implement the loose aim stuff. So, this code remained as vestigial. Removing it.

2019-12-19 20:28 UTC, pravusjif approved these changes
Tested the build and it looks good

2019-12-19 21:14 UTC, merged