fix: BiW Catalog and Inspector (fixes and improvements)
decentraland/explorer pull request #2327
Opened 2021-04-27 09:56 UTC by sandrade-dcl

### Fixes
- [ ] Expand/Collapse makes categories to display the asset packs
- [ ] Missing collapse arrow in the entity inspector menu (item selected)
- [ ] Back button in collection breaks if you navigate / collapse / search

### Improvements
- [ ] Replace icons by tabs (Categories, Asset Packs, Favorites)
![image.png](https://images.zenhubusercontent.com/603cdb58edb53386a3d0d8d5/fa74d357-010b-46c2-b32c-dee77328cfbb)
Refer to Figma to check what happen while the panel is resized
- [ ] Change Asset Packs to display as list view
- [ ] Delete collapse icon and place Catalog Icon in its place
- [ ] Delete collapse icon in Entity List
- [ ] While selecting more than one entity, it should show the count instead of the Entity Details (2 entities selected)

2021-04-28 08:09 UTC, AjimenezDCL approved these changes
LGTM!

2021-04-28 15:37 UTC, Suduck requested changes
Good job! It feels much more polished right now! I have a couple of request if you don't mind

Can we center the assets/categories/ favorites in the expandend catalog?
![image](https://user-images.githubusercontent.com/54064092/116431231-e26ef900-a847-11eb-95a2-812b05fdf954.png)

Can we center the text of how many entities are selected?
![image](https://user-images.githubusercontent.com/54064092/116431774-5dd0aa80-a848-11eb-9f97-bdc529b728d7.png)

2021-04-28 18:00 UTC, sandrade-dcl commented
@Suduck: talking with Álvaro, we have finally decided to set an always fixed title ("Entity Details") for the `EntityInformationView`:
![image](https://user-images.githubusercontent.com/64659061/116450300-68486f80-a85b-11eb-97f7-1c7d058e0270.png)
![image](https://user-images.githubusercontent.com/64659061/116450397-8c0bb580-a85b-11eb-9196-8c3f81d82be0.png)

Done in https://github.com/decentraland/explorer/pull/2327/commits/3fb581c85b03806af9afc2e2d055a27c407a6f35

And about the assets/categories/favorites selector in the expanded catalog view, he specified me to keep it to the left side of the window (that is something more similar to the v5 of the figma).

2021-04-29 03:49 UTC, pravusjif approved these changes

2021-04-29 08:27 UTC, Suduck approved these changes

2021-04-29 08:33 UTC, merged