feat: biw smart item compatibility with builder
decentraland/explorer pull request #2465
Opened 2021-07-05 14:52 UTC by Suduck

# What? 

This PR adds a way to don't lose the information of Builder about smart items when travelling to the renderer.

# Why? 

This will make the compatibility between builder and builder in world even more robust since you won't lose your smart item data when you open the scene in builder in world

2021-07-06 12:54 UTC, kuruk-mm requested changes

2021-07-06 12:54 UTC, kuruk-mm commented on kernel/packages/shared/apis/SceneStateStorageController/StorableSceneStateTranslation.ts
> +    let entityname = entityId
```suggestion
    let entityName = entityId
```

2021-07-06 12:54 UTC, kuruk-mm commented on kernel/packages/shared/apis/SceneStateStorageController/StorableSceneStateTranslation.ts
> +        entityname = component.data.builderValue
```suggestion
        entityName = component.data.builderValue
```

2021-07-06 12:54 UTC, kuruk-mm commented on kernel/packages/shared/apis/SceneStateStorageController/StorableSceneStateTranslation.ts
> +      name: entityname
```suggestion
      name: entityName
```

2021-07-06 20:15 UTC, kuruk-mm approved these changes
The code looks good. I didn't test it.

2021-07-08 08:47 UTC, sandrade-dcl approved these changes
LGTM!

2021-07-08 11:44 UTC, merged