feat: avatar expressions
decentraland/explorer pull request #329
Opened 2020-01-09 13:27 UTC by AjimenezDCL

https://app.zenhub.com/workspaces/explorer-5dc988c462b0b700019b0b42/issues/decentraland/explorer/187

This PR will implement the quick MVP to give users a feeling for the feature. It's a non-scalable feature that needs redesign once we implement it fully. https://docs.google.com/document/d/1nQp0-tuQ_OXSD7mUGqIMlymoVi5-fcO29gXq4UTvStc/edit?folder=0APiAX2_Wo71IUk9PVA#heading=h.fjwzki9j0g46

2020-01-14 15:57 UTC, BrianAmadori approved these changes
Awesome job!. Wasn't able to test it first hand but the code looks good. Just left a question.

2020-01-14 15:57 UTC, BrianAmadori commented on kernel/packages/shared/comms/PresenceReporter.ts
> -export type UserId = string
Why is this being deleted?

2020-01-14 20:01 UTC, pravusjif approved these changes

2020-01-14 20:03 UTC, pbosio approved these changes

2020-01-16 12:05 UTC, eordano commented
Pending:

- [x] Chat trigger doesn't trigger animation locally
- [ ] Bug on components on initialization
- [ ] Actual 3D animations by Shibu

2020-01-16 19:27 UTC, eordano commented
@AjimenezDCL can you fix the merge conflicts?

2020-01-16 19:30 UTC, eordano requested changes
- [x] @eordano: Fix local `/emote` not triggering animation
- [ ] @eordano: Fix error message on component initialization -- maybe AvatarComponent default values?
- [x] @AjimenezDCL: rebase & solve conflicts with master
- [ ] @ShibuyaMartin  and @AjimenezDCL : add final animations

2020-01-31 13:22 UTC, eordano commented on kernel/packages/shared/comms/PresenceReporter.ts
> -export type UserId = string
File was deleted in another pr I think

2020-01-31 13:23 UTC, eordano approved these changes

2020-01-31 14:46 UTC, BrianAmadori approved these changes

2020-01-31 14:46 UTC, BrianAmadori commented on unity-client/Assets/Scripts/MainScripts/DCL/Components/Avatar/AvatarRenderer.cs
> +            var mainSkinnedRenderer = bodyShapeController.skinMeshRendered;
```suggestion
            var mainSkinnedRenderer = bodyShapeController.skinnedMeshRenderer;
```

2020-01-31 14:46 UTC, BrianAmadori commented on unity-client/Assets/Scripts/MainScripts/DCL/Controllers/PlayerAvatarController/ExpressionsHotKeyController.cs
> +        return;
Can be have some type of constant here? After this is merged it can be a bit cumbersome to find all the code to re-enable them again otherwise.

2020-01-31 15:04 UTC, pravusjif commented on unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/ExpressionsHUD/ExpressionsHUDController.cs
> +        UserProfile.GetOwnUserProfile().SetAvatarExpression(id);
Is there any way we can cache the `UserProfile.GetOwnUserProfile()` result somewhere to avoid fetching this every time an expression is used?

2020-01-31 15:06 UTC, pravusjif approved these changes

2020-01-31 15:25 UTC, AjimenezDCL commented on unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/ExpressionsHUD/ExpressionsHUDController.cs
> +        UserProfile.GetOwnUserProfile().SetAvatarExpression(id);
It's cached in UserPofile already =D

2020-01-31 19:32 UTC, merged