feat: tweaks of performance to the bus priorities
decentraland/explorer pull request #333
Opened 2020-01-12 03:42 UTC by eordano

[This PR started as only moving code around: behavior should be pretty similar]

I was having a hard time visualizing bus queue priorities: I think this slightly improves the visibility of that, what do you think @BrianAmadori @pravusjif? I tried to use less lines so that the priority between queues is clearly distinguished. I made some changes that I hope should improve start up time.

2020-01-12 12:41 UTC, eordano commented on unity-client/Assets/Scripts/MainScripts/DCL/Controllers/Scene/MessagingControllersManager.cs
> +                if (ProcessBus(bus, ref prevTimeBudget, out yieldReturn))
What is `yieldReturn` used for?

2020-01-12 16:28 UTC, eordano commented on unity-client/Assets/Scripts/MainScripts/DCL/Controllers/Scene/MessagingControllersManager.cs
> -                yieldReturn = null;
Can you advise on whether this is correct?

2020-01-12 16:28 UTC, eordano commented on unity-client/Assets/Scripts/MainScripts/DCL/Controllers/Scene/MessagingControllersManager.cs
> +                // This loop makes sure that queues are emptied out in the correct order.
Please read these comments carefully!

2020-01-12 19:32 UTC, eordano commented on unity-client/Assets/Scripts/MainScripts/DCL/Controllers/Scene/MessagingControllersManager.cs
> +                start = Time.realtimeSinceStartup;
```suggestion
                start = Time.realtimeSinceStartup;
                prevTimeBudget = INIT_MSG_BUS_BUDGET_MAX;
```

2020-01-12 19:33 UTC, eordano commented on unity-client/Assets/Scripts/MainScripts/DCL/Controllers/Scene/MessagingControllersManager.cs
> +                // This loop makes sure that queues are emptied out in the correct order.
If I messed up with the description please correct me. I'm pretty sure I have a bad mental model.

2020-01-13 14:39 UTC, eordano commented on unity-client/Assets/Scenes/InitialScene.unity
> +  environment: 4
This switches to `.org` by default

2020-01-13 18:21 UTC, BrianAmadori commented on unity-client/Assets/Scripts/MainScripts/DCL/Controllers/Scene/MessagingControllersManager.cs
> +                if (ProcessBus(bus, ref prevTimeBudget, out yieldReturn))
Some components may have updates that takes more than one frame (mostly UI ones). In that case they provide an `IEnumerator` that should be yielded in order for those components to be updated correctly, that `IEnumerator` is filled out in that `yieldReturn` variable.

I'm reading changes from many commits ago and i'm noticing this `yieldReturn` is never yielded, this is a case of "Why this was working all this time along?" because not yielding it should break components.

For this to work correctly, we should check for nullity and yield.
```
if (yieldReturn != null) 
    yield yieldReturn;
```

2020-01-13 18:46 UTC, BrianAmadori requested changes

2020-01-13 18:46 UTC, BrianAmadori commented on unity-client/Assets/Scripts/MainScripts/DCL/Controllers/Scene/MessagingControllersManager.cs
> +                while (Time.realtimeSinceStartup - start <= GLOBAL_MAX_MSG_BUDGET)
I'm not sure if this is more readable than having `while (true)` and checking at the end, because we have more than one condition. Moreover, we are missing the `processedBus` check. This is important because this fixed the case of having a big chunk of time doing nothing when no buses have messages.

2020-01-13 18:46 UTC, BrianAmadori commented on unity-client/Assets/Scripts/MainScripts/DCL/Controllers/Scene/MessagingControllersManager.cs
> +                    if (!IsRenderingActivated())
We have evidence that this is actually saving CPU time? Because we are already prioritizing init messages without this code and the load time bottleneck is not on this side but more on download times. This is not needed imho.

2020-01-13 18:46 UTC, BrianAmadori commented on unity-client/Assets/Scripts/MainScripts/DCL/Controllers/Scene/MessagingControllersManager.cs
> +                        // yield return yieldReturn;
I'm reading changes from many commits ago and i'm noticing this yieldReturn is never yielded, this is a case of "Why this was working all this time along?" because not yielding it should break components.

For this to work correctly, we should check for nullity and yield.
```
if (yieldReturn != null) 
    yield yieldReturn;
```
I think this should be done in the outer loop.

2020-01-13 18:46 UTC, BrianAmadori commented on unity-client/Assets/Scripts/MainScripts/DCL/Controllers/Scene/MessagingControllersManager.cs
> -                yieldReturn = null;
This should be cool because the `yieldReturn` is filled out by `bus.ProcessQueue(timeBudget, out yieldReturn);
` line.

2020-01-13 18:46 UTC, BrianAmadori commented on unity-client/Assets/Scripts/MainScripts/DCL/Controllers/Scene/MessagingControllersManager.cs
> +        private bool ProcessEventsFromBus(MessagingController controller, MessagingBus bus, ref float prevTimeBudget, ref IEnumerator yieldReturn)
For consistency sake we should use `out IEnumerator yieldReturn`. The only difference with `ref` is that we expect a new value to be filled out instead of modifying an existing one.

2020-01-13 18:46 UTC, BrianAmadori commented on unity-client/Assets/Scripts/MainScripts/DCL/Controllers/Scene/MessagingControllersManager.cs
> +        private bool ProcessEventsFromBus(MessagingController controller, MessagingBus bus, ref float prevTimeBudget, ref IEnumerator yieldReturn)
This abstraction looks like its saving a lot of code and that's generally good, but be very careful with it as it this is a critical section of the code. Naive calls like the ones to this method may introduce unwanted bottlenecks. I had to make a lot of micro-optimizations to this code in my last performance commit, and this will introduce repeated `if` calls in cases that were grouped. Please profile.

2020-01-13 18:46 UTC, BrianAmadori commented on unity-client/Assets/Scripts/MainScripts/DCL/Controllers/Scene/MessagingControllersManager.cs
> +                // It would be good to check if there's an alternative implementation of this,
Please let's keep code quality discussions in this medium instead of code comments. Please check the `processedBus` check in the former version of this file for empty queue optimization.

2020-01-13 19:09 UTC, eordano commented on unity-client/Assets/Scripts/MainScripts/DCL/Controllers/Scene/MessagingControllersManager.cs
> +                while (Time.realtimeSinceStartup - start <= GLOBAL_MAX_MSG_BUDGET)
I replaced the need for processedBus with "continue" and a yield null at the end

2020-01-14 19:28 UTC, closed without merging