feat: quality settings
decentraland/explorer pull request #337
Opened 2020-01-12 17:54 UTC by pbosio

#132

2020-01-13 19:05 UTC, BrianAmadori commented on unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/SettingsHUD/Settings.cs
> +            if (OnQualitySettingsChanged != null) OnQualitySettingsChanged(settings);
```suggestion
            OnQualitySettingsChanged?.Invoke(settings);
```

2020-01-13 19:05 UTC, BrianAmadori commented on unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/SettingsHUD/Settings.cs
> +            if (OnGeneralSettingsChanged != null) OnGeneralSettingsChanged(settings);
```suggestion
            OnGeneralSettingsChanged?.Invoke(settings);
```

2020-01-13 19:05 UTC, BrianAmadori commented on unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/SettingsHUD/SettingsGeneralView.cs
> +                int antialisaingValue = 1 << (int)value;
```suggestion
                int antiAliasingValue = 1 << (int)value;
```

2020-01-13 19:05 UTC, BrianAmadori commented on unity-client/Assets/Scripts/MainScripts/DCL/Helpers/UIHelpers/SpinBoxPresetted.cs
> +    public class OnValueChanged : UnityEvent<int>
This is absolutely necessary? We are using it to bind events from editor? I see a lot of `AddListener` calls using code.

2020-01-13 20:03 UTC, pbosio commented on unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/SettingsHUD/Settings.cs
> +            if (OnQualitySettingsChanged != null) OnQualitySettingsChanged(settings);
done

2020-01-13 20:03 UTC, pbosio commented on unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/SettingsHUD/Settings.cs
> +            if (OnGeneralSettingsChanged != null) OnGeneralSettingsChanged(settings);
done

2020-01-13 20:03 UTC, pbosio commented on unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/SettingsHUD/SettingsGeneralView.cs
> +                int antialisaingValue = 1 << (int)value;
done

2020-01-13 20:05 UTC, pbosio commented on unity-client/Assets/Scripts/MainScripts/DCL/Helpers/UIHelpers/SpinBoxPresetted.cs
> +    public class OnValueChanged : UnityEvent<int>
Being a script for a UI behavior I choose the same approach that Unity uses for UI elements that have a callback when it value change and in any case, maybe, someone wants to assign it callback through the editor's inspector

2020-01-14 15:31 UTC, BrianAmadori commented on unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/SettingsHUD/Test/GeneralSettingsShould.cs
> +            yield return SetUp_CharacterController();
Maybe we can remove those `SetUp_` calls, as the test doesn't seem to need them.

2020-01-14 15:31 UTC, BrianAmadori commented on unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/SettingsHUD/Test/GeneralSettingsShould.cs
> +            SetupAndCheckReferences();
Those checks should be under another test instead of here.

2020-01-14 15:31 UTC, BrianAmadori commented on unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/SettingsHUD/Test/GeneralSettingsShould.cs
> +            Assert.IsTrue(DCL.Settings.i.qualitySettings.Equals(testQualitySettings), "Quality Setting missmatch");
The correct spelling is `mismatch`

2020-01-14 15:41 UTC, BrianAmadori requested changes
Please make sure the starting preset has the same values as the default ones set in the LWRP asset. For instance, I see that we are setting AA 8x by default when it should be 2x.

Also, the window UX is not working properly. The settings should be applied instantly (as soon as we touch the sliders/toggles) and:

- Be confirmed via the `OK` button in the settings window
- Be reverted via the `X` or `Cancel` button

2020-01-14 17:49 UTC, pravusjif approved these changes

2020-01-14 18:34 UTC, pbosio commented
> Please make sure the starting preset has the same values as the default ones set in the LWRP asset. For instance, I see that we are setting AA 8x by default when it should be 2x.
> 
> Also, the window UX is not working properly. The settings should be applied instantly (as soon as we touch the sliders/toggles) and:
> 
>     * Be confirmed via the `OK` button in the settings window
> 
>     * Be reverted via the `X` or `Cancel` button

Done

2020-01-14 18:35 UTC, pbosio commented on unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/SettingsHUD/Test/GeneralSettingsShould.cs
> +            Assert.IsTrue(DCL.Settings.i.qualitySettings.Equals(testQualitySettings), "Quality Setting missmatch");
done

2020-01-14 18:35 UTC, pbosio commented on unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/SettingsHUD/Test/GeneralSettingsShould.cs
> +            SetupAndCheckReferences();
done. added new test to check that references are set

2020-01-14 18:35 UTC, pbosio commented on unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/SettingsHUD/Test/GeneralSettingsShould.cs
> +            yield return SetUp_CharacterController();
removed those SetUp_

2020-01-14 20:35 UTC, BrianAmadori approved these changes

2020-01-16 16:00 UTC, merged