fix: remove MonoBehaviour inheritance from LoadWrapper classes
decentraland/explorer pull request #417
Opened 2020-01-23 19:34 UTC by BrianAmadori

This is the first step in reducing the overhead of `AddComponent` calls.

- All the `LoadWrapper` instances are stored in the `LoadableShape.attachedLoaders` dictionary and retrieved using `GetLoaderForEntity`. Having a static dictionary in the base class with `gameObject` as key, means than any given entity can only have one `LoadWrapper` attached.

- As all `LoadWrapper` classes are not `MonoBehaviour` anymore, the `OnDestroy` method was removed. This should not be an issue because we are already ensuring `Unload` gets called before destroying any entity through the `DetachShape` calls.

- I'm still on the fence of removing the need for having to create a new `meshRootGameObject` instance. As all the GLTF/AB we are loading already have a container object.

2020-01-27 21:57 UTC, pravusjif commented on unity-client/Assets/Scripts/MainScripts/DCL/Components/LoadableShapes/LoadableShape.cs
> +                }
Can't we do something like the following here?
```
LoadWrapperType loadableShape = GetLoaderForEntity(entity) as LoadWrapperType;

if (loadableShape == null)
{
    loadableShape = new LoadWrapperType();
    attachedLoaders.Add(entity.meshRootGameObject, loadableShape);
}
```

2020-01-27 21:59 UTC, pravusjif commented on unity-client/Assets/Scripts/MainScripts/DCL/Components/LoadableShapes/NFTShape/NFTShape.cs
> +                }
same question as in LoadableShape.cs here

2020-01-27 22:08 UTC, pravusjif requested changes

2020-01-27 22:08 UTC, pravusjif commented on unity-client/Assets/Scripts/MainScripts/DCL/Components/LoadableShapes/LoadWrapper/LoadWrapper_NFT.cs
> +            loaderController.backgroundColor = backgroundColor;
I'm confused about this 2 values, shouldn't this be configured from the shape class itself using the model parsed from the kernel?

2020-01-27 22:22 UTC, AjimenezDCL commented on unity-client/Assets/Scripts/MainScripts/DCL/Components/LoadableShapes/LoadableShape.cs
> +                }
Haven't check the PR yet, but in any case you can avoid the null check of @pravusjif suggestion with:
```
if (GetLoaderForEntity(entity) is LoadWrapperType loadableShape)
{
    loadableShape = new LoadWrapperType();
    attachedLoaders.Add(entity.meshRootGameObject, loadableShape);
}
```

EDIT: This is nonsense, ignore it

2020-01-28 09:59 UTC, AjimenezDCL approved these changes

2020-01-28 09:59 UTC, AjimenezDCL commented on unity-client/Assets/Scripts/MainScripts/DCL/Components/LoadableShapes/LoadWrapper/LoadWrapper_NFT.cs
> +            loaderController.collider.enabled = withCollisions;
Do we need a null check here? Could the `meshRootGameObject` not have the component?

2020-01-28 09:59 UTC, AjimenezDCL commented on unity-client/Assets/Scripts/MainScripts/DCL/Components/LoadableShapes/LoadWrapper/LoadWrapper_OBJ.cs
> +            objLoaderComponent.OnFinishedLoadingAsset += () => OnSuccess(this);
I see this callback being subscribed to `objLoaderComponent.OnFinishedLoadingAsset` but not being unsubscribed. Are we controlling that use-case somewhere else?

Otherwise we could have a delegate as a field in the class, add `OnSuccess(this)` to the delegate and the delegate to `objLoaderComponent.OnFinishedLoadingAsset`.

2020-01-28 12:35 UTC, pravusjif commented on unity-client/Assets/Scripts/MainScripts/DCL/Components/LoadableShapes/LoadableShape.cs
> +                }
what kind of magic is that? XD.
Also, that code block shoud run when the GetLoaderForEntity(entity) **is not** LoadWrapperType, would `if(!(GetLoaderForEntity(entity) is LoadWrapperType) loadableShape)` work? I don't know if this convinces me as it is kind of confusing XD

2020-01-28 13:14 UTC, AjimenezDCL commented on unity-client/Assets/Scripts/MainScripts/DCL/Components/LoadableShapes/LoadableShape.cs
> +                }
Oh... you are right.

I thought the condition was `if (loadableShape != null)`. My fault!

2020-01-28 16:14 UTC, BrianAmadori commented on unity-client/Assets/Scripts/MainScripts/DCL/Components/LoadableShapes/LoadWrapper/LoadWrapper_NFT.cs
> +            loaderController.backgroundColor = backgroundColor;
Yes, the shape class pass the values from the model to these two values. Had to make the params pass around this way for scoping purposes.

2020-01-28 16:15 UTC, BrianAmadori commented on unity-client/Assets/Scripts/MainScripts/DCL/Components/LoadableShapes/LoadWrapper/LoadWrapper_OBJ.cs
> +            objLoaderComponent.OnFinishedLoadingAsset += () => OnSuccess(this);
Let me check. The `OBJ` stuff is pretty outdated and should be removed, but in the meantime i'll try to apply a workaround.

2020-01-28 16:17 UTC, BrianAmadori commented on unity-client/Assets/Scripts/MainScripts/DCL/Components/LoadableShapes/LoadableShape.cs
> +                }
Cool suggestions guys. The `loadableShape` must be stored, so I think the inline `is` will not work. We should use that new C# idiom more often though. Let me check what I can do with this expression.

2020-01-28 16:17 UTC, BrianAmadori commented on unity-client/Assets/Scripts/MainScripts/DCL/Components/LoadableShapes/LoadWrapper/LoadWrapper_NFT.cs
> +            loaderController.collider.enabled = withCollisions;
Maybe. Let me check.

2020-01-28 18:02 UTC, BrianAmadori commented on unity-client/Assets/Scripts/MainScripts/DCL/Components/LoadableShapes/LoadWrapper/LoadWrapper_NFT.cs
> +            loaderController.collider.enabled = withCollisions;
This component is added here:
https://github.com/decentraland/explorer/blob/fac3bdacd71d925433594d9ad4a43a0ea7707f14/unity-client/Assets/Scripts/MainScripts/DCL/Components/LoadableShapes/NFTShape/NFTShape.cs#L26
Just before calling this code. That prefab contains the `NFTShapeLoaderController` component. Not sure of a better way of doing this.

2020-01-28 18:13 UTC, AjimenezDCL commented on unity-client/Assets/Scripts/MainScripts/DCL/Components/LoadableShapes/LoadWrapper/LoadWrapper_NFT.cs
> +            loaderController.collider.enabled = withCollisions;
Maybe we can somehow abort the execution safely if the component is not found. To avoid crashes.

2020-01-28 19:35 UTC, BrianAmadori commented on unity-client/Assets/Scripts/MainScripts/DCL/Components/LoadableShapes/LoadWrapper/LoadWrapper_NFT.cs
> +            loaderController.collider.enabled = withCollisions;
ok, added an early exit just in case.

2020-01-28 19:59 UTC, pravusjif approved these changes

2020-01-28 20:06 UTC, merged