test: simplifying logic on controllers
decentraland/explorer pull request #425
Opened 2020-01-25 21:47 UTC by eordano

Simplify bus controller to try and avoid logic errors when messages are pending

2020-01-25 21:50 UTC, eordano commented on unity-client/Assets/Scripts/MainScripts/DCL/Controllers/Scene/MessagingControllersManager.cs
> -        public void RefreshControllerEnabledState(MessagingController controller)
This is the most important change in the PR. I think that the `enabled` check here was preventing things from becoming enabled.

2020-01-25 21:51 UTC, eordano commented on unity-client/Assets/Scripts/MainScripts/DCL/Controllers/Scene/MessagingControllersManager.cs
> -                timeBudgetCounter = RenderingController.i.renderingEnabled ? MAX_GLOBAL_MSG_BUDGET : float.MaxValue;
Float.maxValue caused stuttering in the loading screen

2020-01-25 21:52 UTC, eordano commented on unity-client/Assets/Scripts/MainScripts/DCL/Controllers/Scene/MessagingControllersManager.cs
> -            PopulateBusesToBeProcessed();
By replacing this for a dirty flag we prevent sorting unnecessarily

2020-01-25 21:52 UTC, eordano commented on unity-client/Assets/Scripts/MainScripts/DCL/Controllers/Scene/MessagingControllersManager.cs
> -        private const float MAX_SYSTEM_MSG_BUDGET_FOR_FAR_SCENES = 0.003f;
This was not being used

2020-01-25 21:54 UTC, eordano commented on unity-client/Assets/Scripts/MainScripts/DCL/Controllers/Scene/MessagingBus.cs
> -                    MessagingControllersManager.i.MarkBusesDirty();
Single responsibility principle: owner should know when to mark their buses dirty (this simplifies the number of assumptions the bus has to make about the controller)

2020-01-25 21:55 UTC, eordano commented on unity-client/Assets/Scripts/MainScripts/DCL/Controllers/Scene/MessagingBus.cs
> -        public float timeBudget
Time budget is local to ProcessBus now

2020-01-27 14:53 UTC, AjimenezDCL requested changes

2020-01-27 14:53 UTC, AjimenezDCL commented on unity-client/Assets/Scripts/MainScripts/DCL/Controllers/Scene/MessagingBus.cs
> +        private readonly LinkedList<QueuedSceneMessage> pendingMessages = new LinkedList<QueuedSceneMessage>();
The fields are not following the naming convention (`camelCase`).

Is the conversion from variables to getters really needed?

2020-01-27 14:53 UTC, AjimenezDCL commented on unity-client/Assets/Scripts/MainScripts/DCL/Controllers/Scene/MessagingBus.cs
> +                        SceneController.i.OnMessageWillQueue?.Invoke(sm.method);
I'd keep the null-conditional operator to avoid nesting
`SceneController.i?.OnMessageWillQueue?.Invoke(sm.method);`

2020-01-27 14:53 UTC, AjimenezDCL commented on unity-client/Assets/Scripts/MainScripts/DCL/Controllers/Scene/MessagingBus.cs
> +            while (timeBudget != 0 && pendingMessages.Count > 0 && Time.realtimeSinceStartup - startTime < timeBudget)
Why has been this `enabled` condition removed?

2020-01-27 14:53 UTC, AjimenezDCL commented on unity-client/Assets/Scripts/MainScripts/DCL/Controllers/Scene/MessagingController.cs
> +        private QueueState CurrentQueueState { get; set; }
Naming convention => `camelCase`

2020-01-27 14:53 UTC, AjimenezDCL commented on unity-client/Assets/Scripts/MainScripts/DCL/Controllers/Scene/MessagingController.cs
> +            using (var iterator = messagingBuses.GetEnumerator()) {
Code convention: Braces must be in the next line

2020-01-27 14:53 UTC, AjimenezDCL commented on unity-client/Assets/Scripts/MainScripts/DCL/Controllers/Scene/MessagingControllersManager.cs
> +        private const float GLTF_BUDGET_MAX = 0.008f;
I'd separate this into 2 PRs, one for simplifying the logic and other one to tweak the values.

2020-01-27 14:53 UTC, AjimenezDCL commented on unity-client/Assets/Scripts/MainScripts/DCL/Controllers/Scene/MessagingControllersManager.cs
> +        public bool HasPendingMessages => pendingMessagesCount > 0;
Name Convention => `camelCase`

2020-01-27 14:53 UTC, AjimenezDCL commented on unity-client/Assets/Scripts/MainScripts/DCL/Controllers/Scene/MessagingControllersManager.cs
> +        public bool IsRunning { get { return mainCoroutine != null; } }
Code Convention

2020-01-27 14:53 UTC, AjimenezDCL commented on unity-client/Assets/Scripts/MainScripts/DCL/Controllers/Scene/MessagingControllersManager.cs
> +        private readonly List<MessagingController> sortedControllers = new List<MessagingController>();
Is there any reason behind this change?

2020-01-27 14:53 UTC, AjimenezDCL commented on unity-client/Assets/Scripts/MainScripts/DCL/Controllers/Scene/MessagingControllersManager.cs
> +            bool currentSceneControllerActive = currentSceneController != null;
Is it safe to drop the `enabled` condition?

2020-01-27 14:53 UTC, AjimenezDCL commented on unity-client/Assets/Scripts/MainScripts/DCL/Controllers/Scene/MessagingControllersManager.cs
> +                timeBudgetCounter = RenderingController.i.renderingEnabled ? MAX_GLOBAL_MSG_BUDGET : MAX_GLOBAL_MSG_BUDGET_WHEN_INIT;
I'd split the PR into tweaking and simplifying

2020-01-27 14:53 UTC, AjimenezDCL commented on unity-client/Assets/Scripts/MainScripts/DCL/Controllers/Scene/MessagingControllersManager.cs
> +            if (bus.PendingMessagesCount <= 0)
Is it safe to drop the `enabled` condition?

2020-01-27 14:53 UTC, AjimenezDCL commented on unity-client/Assets/Scripts/MainScripts/DCL/Controllers/Scene/MessagingControllersManager.cs
> -        public void RefreshControllerEnabledState(MessagingController controller)
This function will only disable the controller. 

Besides, is it safe to remove this code? it seems like we were using the `enabled` flag in core parts of the messaging system.

2020-01-27 14:53 UTC, AjimenezDCL commented on unity-client/Assets/Scripts/MainScripts/DCL/Controllers/Scene/SceneController.cs
> +        public string CurrentSceneId { get; private set; }
Code convention

2020-01-27 15:39 UTC, eordano commented on unity-client/Assets/Scripts/MainScripts/DCL/Controllers/Scene/MessagingBus.cs
> +        private readonly LinkedList<QueuedSceneMessage> pendingMessages = new LinkedList<QueuedSceneMessage>();
I wanted to change to getters to make `set` private, what do you think of that?

I'll revert the convention problem, my apologies!

2020-01-27 15:43 UTC, eordano commented on unity-client/Assets/Scripts/MainScripts/DCL/Controllers/Scene/MessagingControllersManager.cs
> -        public void RefreshControllerEnabledState(MessagingController controller)
I keep seeing regressions regarding this `enabled` condition.

Most importantly, when walking in the world, it seems that the bus controller never gets to become `enabled`. The experience is: there are green blockers in the horizon that are never processing messages. You can see that in .zone today, walk across one scene boundary and see a green blocker that never gets the messages processed.

By never considering whether the bus is `enabled` or not, and letting the bus handle that, this trades less performance for an easier to follow logic on whether the messages from the bus will be processed (they will always be processed, and if they should not be, it's the responsibility of the Bus to know that)

2020-01-27 15:48 UTC, BrianAmadori requested changes

2020-01-27 15:48 UTC, BrianAmadori commented on unity-client/Assets/Scripts/MainScripts/DCL/Controllers/PointerEventsController.cs
> +                    string sceneId = SceneController.i.CurrentSceneId;
We use lower camel case for field names. This is a bit against the default C# naming convention but we already took that road.

2020-01-27 15:48 UTC, BrianAmadori commented on unity-client/Assets/Scripts/MainScripts/DCL/Controllers/Scene/MessagingControllersManager.cs
> +                busesToProcess.Add(uiSceneController.systemBus);
System buses should always be processed lastly because the throughtput is always busy. If they aren't last there's the chance of the budget getting filled out with system messages constantly and never reaching init messages ones.

2020-01-27 15:48 UTC, BrianAmadori commented on unity-client/Assets/Scripts/MainScripts/DCL/Controllers/Scene/MessagingControllersManager.cs
> -                timeBudgetCounter = RenderingController.i.renderingEnabled ? MAX_GLOBAL_MSG_BUDGET : float.MaxValue;
With this change the loading screen will last longer. Remember that our main objective is to get the loading time as short as possible. I'd say that having a few stutters in between is a concession we can allow. In any case I'd put the `MAX_GLOBAL_MSG_BUDGET_WHEN_INIT` to cap the stutters to a single second or 1/10th second to limit stutters, but no shorter than that.

2020-01-27 15:48 UTC, BrianAmadori commented on unity-client/Assets/Scripts/MainScripts/DCL/Controllers/Scene/MessagingController.cs
> +            // TODO(Brian, 2020/Jan/25): Explain this assertion better -^
This came because after the UI bus finishes processing its messages is not used anymore, so all the checks against the UI buses stuff are kind of unneeded overhead. This isn't so terrible now because we are spreading the bus checks, but this design still looks iffy to me.

2020-01-27 15:48 UTC, BrianAmadori commented on unity-client/Assets/Scripts/MainScripts/DCL/Controllers/Scene/MessagingControllersManager.cs
> +            bool uiSceneControllerActive = uiSceneController != null;
The `enabled` check is here because we don't want the `for` statement in the coroutine to process more buses than it should. Disabling it we are effectively reducing the performance. I don't see any reason to remove this.

2020-01-27 15:49 UTC, BrianAmadori commented on unity-client/Assets/Scripts/MainScripts/DCL/Controllers/Scene/MessagingBus.cs
> -                    MessagingControllersManager.i.MarkBusesDirty();
Agreed, but please make a proper fix. Removing the enabled logic is not the solution.

2020-01-27 15:51 UTC, AjimenezDCL commented on unity-client/Assets/Scripts/MainScripts/DCL/Controllers/Scene/MessagingBus.cs
> +        private readonly LinkedList<QueuedSceneMessage> pendingMessages = new LinkedList<QueuedSceneMessage>();
We dont really have a convention about Fields vs Properties, I was just curious about the change and the scope of the PR, in any case I prefer it this way to enforce encapsulation..

As a side note, Unity cannot serialize properties, in this case it doesnt matter since is not a `[Serializable]` nor a `Monobehaviour` class,

2020-01-27 16:35 UTC, closed without merging