feat: airdrop
decentraland/explorer pull request #442
Opened 2020-01-29 04:47 UTC by eordano

2020-02-04 16:49 UTC, BrianAmadori requested changes

2020-02-04 16:49 UTC, BrianAmadori commented on unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/AirdroppingHUD/Tests/AirdroppingHUDView_Should.cs
> +        yield return base.SetUp();
Are we sure the `base.SetUp` is needed for those tests?

2020-02-04 16:49 UTC, BrianAmadori commented on unity-client/Assets/Textures/Airdropping.meta
> +fileFormatVersion: 2
Those assets should be under `...s/Scripts/MainScripts/DCL/Controllers/HUD/AirdroppingHUD` with the animations and such.

2020-02-04 17:43 UTC, AjimenezDCL commented on unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/AirdroppingHUD/Tests/AirdroppingHUDView_Should.cs
> +        yield return base.SetUp();
Yes, to have the scene creation and such. Take a look at the overrided property `justSceneSetUp`. This will create a light setup

2020-02-04 18:51 UTC, AjimenezDCL commented on unity-client/Assets/Textures/Airdropping.meta
> +fileFormatVersion: 2
Done

2020-02-05 15:54 UTC, BrianAmadori approved these changes

2020-02-05 17:18 UTC, pravusjif commented on kernel/packages/shared/apis/ChatController.ts
> +    this.addChatCommand('airdrop', 'fake an airdrop', () => {
should we remove this test command before merging?

2020-02-05 17:42 UTC, pravusjif approved these changes

2020-02-05 17:42 UTC, pravusjif commented
Tested in build using the `/airdrop` chat command for the fake airdrop, works fine

2020-02-05 18:05 UTC, AjimenezDCL commented on kernel/packages/shared/apis/ChatController.ts
> +    this.addChatCommand('airdrop', 'fake an airdrop', () => {
@eordano

2020-02-06 13:06 UTC, merged