feat: tutorial unity-side
decentraland/explorer pull request #447
Opened 2020-01-30 16:13 UTC by pbosio

2020-01-31 20:32 UTC, BrianAmadori requested changes

2020-01-31 20:32 UTC, BrianAmadori commented on unity-client/Assets/Tutorial/Scripts/TutorialStages/GenesisPlazaStageController.cs
> +    private void ShowWellcomeToast()
```suggestion
    private void ShowWelcomeToast()
```

2020-01-31 20:32 UTC, BrianAmadori commented on unity-client/Assets/Tutorial/Scripts/TutorialStages/GenesisPlazaStageController.cs
> +        string notificationText = $"Wellcome, {UserProfile.GetOwnUserProfile().userName}!";
```suggestion
        string notificationText = $"Welcome, {UserProfile.GetOwnUserProfile().userName}!";
```

2020-01-31 20:32 UTC, BrianAmadori commented on unity-client/Assets/Tutorial/Scripts/TutorialStages/GenesisPlazaStageController.cs
> +            notificationText += $" You are in {parcelName} {currentCoords.x}, {currentCoords.y}";
Maybe this would get more clean (and easier to localize later) if we extract those literals to variables.

2020-01-31 20:32 UTC, BrianAmadori commented on unity-client/Assets/Tutorial/Scripts/TutorialStages/GenesisPlazaStageController.cs
> +            timer = 5
This `5` is better as a constant?

2020-01-31 20:32 UTC, BrianAmadori commented on unity-client/Assets/Tutorial/Scripts/TutorialTooltip.cs
> +            StartCoroutine(HideAfterAnimation(hideAnimationClip.length));
We should be using animation events instead of this approach. Way cleaner and more performant.

2020-01-31 20:32 UTC, BrianAmadori commented on unity-client/Assets/Tutorial/Scripts/TutorialTooltip.cs
> +    [SerializeField] private AnimationClip showAnimationClip = null;
I think its better if we use a simple mecanim animation override here. If in the future we want to polish the animation flow it'll get easier to maintain. (e.g. if we want some idle animation or similar). 

Also, this'd allow us to remove most of the animation handling code.

2020-01-31 20:32 UTC, BrianAmadori commented on unity-client/Assets/Tutorial/Scripts/TutorialStages/InitialStageController.cs
> +    private IEnumerator StageSecuence()
```suggestion
    private IEnumerator StageSequence()
```

2020-01-31 20:32 UTC, BrianAmadori commented on unity-client/Assets/Tutorial/Scripts/TutorialController.cs
> +    [SerializeField] TutorialStageController initalStage = null;
Its more maintainable to use an array here instead of having each state as a individual reference.

2020-01-31 20:32 UTC, BrianAmadori commented on unity-client/Assets/Tutorial/Scripts/TutorialController.cs
> +    private void StartTutorialStageIfNeeded(int tutorialFlagMask)
Couldn't we just make this an `IEnumerator` and `yield` all the stages out? This could save the `StartCoroutine` boilerplate inside each `StageController`.

2020-01-31 20:32 UTC, BrianAmadori commented on unity-client/Assets/Tutorial/Scripts/TutorialController.cs
> +        if (renderingEnabled && isTutorialEnabled)
We can invert this `if` statement and early exit to avoid nesting.

2020-02-05 19:50 UTC, pravusjif commented on unity-client/Assets/Tutorial/Scripts/TutorialStages/GenesisPlazaStageController.cs
> +            notificationText += $" You are in {parcelName} {currentCoords.x}, {currentCoords.y}";
Let's do this when we prepare everything for localization in the future

2020-02-05 20:14 UTC, pravusjif commented on unity-client/Assets/Tutorial/Scripts/TutorialStages/GenesisPlazaStageController.cs
> +    private void ShowWellcomeToast()
Done

2020-02-05 20:15 UTC, pravusjif commented on unity-client/Assets/Tutorial/Scripts/TutorialStages/GenesisPlazaStageController.cs
> +        string notificationText = $"Wellcome, {UserProfile.GetOwnUserProfile().userName}!";
Done

2020-02-05 20:15 UTC, pravusjif commented on unity-client/Assets/Tutorial/Scripts/TutorialStages/GenesisPlazaStageController.cs
> +            timer = 5
Done

2020-02-05 20:15 UTC, pravusjif commented on unity-client/Assets/Tutorial/Scripts/TutorialTooltip.cs
> +            StartCoroutine(HideAfterAnimation(hideAnimationClip.length));
Done

2020-02-05 20:19 UTC, pravusjif commented on unity-client/Assets/Tutorial/Scripts/TutorialTooltip.cs
> +    [SerializeField] private AnimationClip showAnimationClip = null;
We are not using mecanim, we are using legacy Animation component. You suggest we make these animations non-legacy (by toggling the bool in unity debug mode) and use an animator with 2 states instead?

2020-02-05 20:40 UTC, pravusjif commented on unity-client/Assets/Tutorial/Scripts/TutorialStages/InitialStageController.cs
> +    private IEnumerator StageSecuence()
Done

2020-02-05 21:01 UTC, pravusjif commented on unity-client/Assets/Tutorial/Scripts/TutorialController.cs
> +        if (renderingEnabled && isTutorialEnabled)
Done

2020-02-05 21:49 UTC, BrianAmadori commented on unity-client/Assets/Tutorial/Scripts/TutorialTooltip.cs
> +    [SerializeField] private AnimationClip showAnimationClip = null;
exactly

2020-02-06 12:40 UTC, pravusjif commented on unity-client/Assets/Tutorial/Scripts/TutorialController.cs
> +    [SerializeField] TutorialStageController initalStage = null;
In that case, to avoid having "hardcoded TutorialFlags" on the different array elements based on index in `CreateStagesChainOfResponsibility()` (we'd setup each stage using the array elements in the following way: 
```
private void CreateStagesChainOfResponsibility()
    {
        // 1st stage - initialStage
        firstStage = new GenericSceneStageHandler(TutorialFlags.InitialScene, tutorialStagesArray[0],
            () =>
            {
                HUDController.i?.minimapHud.SetVisibility(false);
            });

        // 2nd stage - LoginRewardAndUserEmail
        var nextStage = firstStage.SetNext(new GenericSceneStageHandler(TutorialFlags.LoginRewardAndUserEmail, tutorialStagesArray[1], null));

        // 3rd stage - ChatAndAvatarExpressions
        nextStage = nextStage.SetNext(new GenericSceneStageHandler(TutorialFlags.ChatAndAvatarExpressions, tutorialStagesArray[2],
            () =>
            {
                HUDController.i?.avatarHud.SetVisibility(false);
                SetChatVisible(false);
                // TODO: hide avatar expressions
                //HUDController.i?.expressionsHud.SetVisibility(false);
            }));
    }
```
) but if some day someone changes the array elements order, it would become a problem) I'd have to create a new mini-class inside TutorialController, with both a reference for the gameobject (as we have now instead of an array, but for each element) and a reference to the `TutorialFlags` corresponding to that stage.

Is that OK with you?

2020-02-06 13:19 UTC, pravusjif commented on unity-client/Assets/Tutorial/Scripts/TutorialController.cs
> +    private void StartTutorialStageIfNeeded(int tutorialFlagMask)
Not sure about this, with the previously implemented "chain of command" I should refactor that to get this working with nested coroutines, is it worth the time?

2020-02-06 14:33 UTC, AjimenezDCL submitted a review, later dismissed

2020-02-06 14:33 UTC, AjimenezDCL commented on kernel/packages/config/index.ts
> +export const TUTORIAL_ENABLED = WORLD_EXPLORER && true
Is the `&& true` needed?

2020-02-06 14:33 UTC, AjimenezDCL commented on unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/AvatarEditorHUD/Scripts/AvatarEditorHUDController.cs
> +    public Action<bool> OnVisibilityChanged;
I dont think this is needed.

The only subscriber is `InitialStageController` and the same script is the one changing the visibility of the `AvatarEditorHUD`.

SetVisibility could be called by Kernel through the HUDController, but in that case, I think this event should be in the HUDController so we don't couple the autonomous HUDs to any external system (that is not HUDController).

2020-02-06 16:13 UTC, BrianAmadori commented on unity-client/Assets/Tutorial/Scripts/TutorialController.cs
> +    [SerializeField] TutorialStageController initalStage = null;
It wouldn't be more simple to just have each stage define its own flag? (i.e. just initialize it in the stage constructor). If for some reason this isn't viable that approach sounds fine.

2020-02-06 16:14 UTC, BrianAmadori commented on unity-client/Assets/Tutorial/Scripts/TutorialController.cs
> +    private void StartTutorialStageIfNeeded(int tutorialFlagMask)
I think we'd reach a far more simpler design, easier to maintain. But if you think it can't be finished by today i'd leave it as it is.

2020-02-06 16:15 UTC, BrianAmadori commented on kernel/packages/config/index.ts
> +export const TUTORIAL_ENABLED = WORLD_EXPLORER && true
We should change this to do a `location.search.indexOf('NO_TUTORIAL') === -1`.

Otherwise it'd give headaches to debug explorer in the future.

2020-02-07 18:02 UTC, BrianAmadori commented on unity-client/Assets/Scripts/MainScripts/DCL/UserProfile/UserProfile.cs
> +    public void SetTutorialFlag(int newTutorialFlagsMask)
Why a bitmask? Why not just a counter?

2020-02-07 20:22 UTC, BrianAmadori commented on unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/AvatarEditorHUD/Scripts/AvatarEditorHUDController.cs
> +    public Action<bool> OnVisibilityChanged;
This is in place because we have to detect somehow when the user closes the avatar hud in order to continue the tutorial, so the check and callback should be in Unity side. Do you have a suggestion to improve this approach with this in mind? (asking honestly because I can't figure out anything from the top of my head).

2020-02-07 21:07 UTC, BrianAmadori approved these changes

2020-02-07 21:11 UTC, merged