feat: player info card (bio, collectibles, block) on click
decentraland/explorer pull request #453
Opened 2020-01-30 20:11 UTC by pravusjif

https://github.com/decentraland/explorer/issues/144

2020-01-30 20:16 UTC, pravusjif commented
OK It's working in editor but no in build.

2020-01-30 21:39 UTC, pravusjif commented
It works fine now.

2020-01-31 13:44 UTC, pravusjif commented on unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/AvatarEditorHUD/Scripts/CharacterPreviewController.cs
> +        return Sprite.Create(screenShot, new Rect(0, 0, screenShot.width, screenShot.height), Vector2.zero);
We should be destroying manually (with Destroy() ) every Sprite we create in runtime, as they are not garbage collected, to avoid memory leaks

2020-01-31 13:48 UTC, AjimenezDCL commented on unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/AvatarEditorHUD/Scripts/CharacterPreviewController.cs
> +        return Sprite.Create(screenShot, new Rect(0, 0, screenShot.width, screenShot.height), Vector2.zero);
It's gonna be hard to find a way to do that. One of these sprites is ending up in the top-right AvatarHUD image.

Let me take a look

2020-01-31 15:00 UTC, BrianAmadori requested changes

2020-01-31 15:00 UTC, BrianAmadori commented on unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/PlayerInfoCardHUD/Tests/PlayerInfoCardHUDViewShould.cs
> +        yield return base.SetUp();
The `base.SetUp` initializes some stuff like the camera. Are we sure we need all of that for this test class? Maybe we can just override it with a lightweight setup. This will execute in all `TestCase` attributes too.

2020-01-31 15:00 UTC, BrianAmadori commented on unity-client/Assets/Scripts/MainScripts/DCL/Controllers/PointerEventsController.cs
> +            }
Just a nitpick but this can be a nice use case for switch pattern matching.

2020-01-31 15:00 UTC, BrianAmadori commented on unity-client/Assets/Scripts/MainScripts/DCL/UserProfile/UserProfile.cs
> +[assembly: InternalsVisibleTo("PlayerInfoCardHUDTests")]
We should move those statements to an `AssemblyInfo.cs` file.

2020-01-31 15:00 UTC, BrianAmadori commented on unity-client/Assets/Scripts/MainScripts/DCL/UserProfile/UserProfileController.cs
> +    public void Do()
This is necessary? If yes, we should rename it to something more descriptive, lie e.g: `Add user profile to catalog`.

2020-01-31 15:00 UTC, BrianAmadori commented on unity-client/Assets/Scripts/MainScripts/DCL/UserProfile/UserProfile.cs
> +        if (model?.snapshots?.face != null)
Maybe is a bit more correct to use a single if here that checks for `model` and `snapshots` != null. We are duplicating checks otherwise.

2020-01-31 15:00 UTC, BrianAmadori commented on unity-client/Assets/Scripts/MainScripts/DCL/UserProfile/UserProfile.cs
>          model.name = newModel?.name;
Its a bit better if we just check for `newModel != null` here once. The check is running like 7 times otherwise (or its optimized away in IL?).

2020-01-31 15:00 UTC, BrianAmadori commented on unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/PlayerInfoCardHUD/Tests/PlayerInfoCardHUDControllerShould.cs
> +        yield return base.SetUp();
The base.SetUp initializes some stuff like the camera. Are we sure we need all of that for this test class? Maybe we can just override it with a lightweight setup. This will execute in all TestCase attributes too.

2020-01-31 15:04 UTC, AjimenezDCL commented on unity-client/Assets/Scripts/MainScripts/DCL/UserProfile/UserProfileController.cs
> +    public void Do()
Oops, I thought i removed all the log/testing code. Sorry

2020-01-31 15:45 UTC, AjimenezDCL commented on unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/PlayerInfoCardHUD/Tests/PlayerInfoCardHUDViewShould.cs
> +        yield return base.SetUp();
It was not necessary, I was scared of avoiding something crucial (like setting up the scene and such).

I'm gonna cherrypick what I need from the base implementation, but as you suggested we should change the base in the future to be able to pick between a lighter setup.

2020-01-31 15:49 UTC, AjimenezDCL commented on unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/PlayerInfoCardHUD/Tests/PlayerInfoCardHUDViewShould.cs
> +        yield return base.SetUp();
Nevermind, I implemented it quickly =D

2020-01-31 15:55 UTC, AjimenezDCL commented on unity-client/Assets/Scripts/MainScripts/DCL/Controllers/PointerEventsController.cs
> +            }
I have no idea why is that in my PR, to be honest xD. Let me research a bit

2020-01-31 17:39 UTC, AjimenezDCL commented on unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/AvatarEditorHUD/Scripts/CharacterPreviewController.cs
> +        return Sprite.Create(screenShot, new Rect(0, 0, screenShot.width, screenShot.height), Vector2.zero);
I cannot find an elegant solution for this, created an issue #459

2020-01-31 17:58 UTC, BrianAmadori approved these changes

2020-02-03 15:00 UTC, merged