feat: tutorial scene integration
decentraland/explorer pull request #458
Opened 2020-01-31 15:34 UTC by pbosio

You can test the tutorial with 

https://explorer.decentraland.zone/branch/feat/kernel-tutorial-scene/index.html?ENV=org&RESET_TUTORIAL

Notes:
* the URL param `RESET_TUTORIAL` resets the user tutorial step, if you finish the tutorial (the daily reward tip is the last one), then you can re-access the url (**without** the `RESET_TUTORIAL` param) and see that the tutorial is not triggered.
* If you access with a user that claimed a name, the claim name panel (after closing the first avatar editor) won't show up, only with no-claimed users (that can be triggered accessing from an incognito window with ENV=zone instead of org)

2020-02-13 14:14 UTC, moliva approved these changes

2020-02-14 10:32 UTC, AjimenezDCL requested changes

2020-02-14 10:32 UTC, AjimenezDCL commented on kernel/packages/decentraland-loader/lifecycle/controllers/download.ts
> +    // stub
What about this? Are we missing something here? If there's something to be implemented here can we change it with a proper // TODO?

2020-02-14 10:32 UTC, AjimenezDCL commented on kernel/packages/decentraland-loader/lifecycle/controllers/download.ts
> +    if (isTutorial()) {
All these checks for tutorial make me think we could implement some inheritance based architecture here. Probably is too much effort and too little gain, but maybe is it worth taking a look into it in the future.

2020-02-14 10:32 UTC, AjimenezDCL commented on unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/AirdroppingHUD/AirdroppingHUDController.cs
> +    public static event System.Action OnAirdropFinished = null;
I really dislike having this event and coupling other classes to AirdroppingHUD. I think a better approach would have been ignoring the huds and such and through inheritance create what was needed for the tutorial, and once the tutorial was finished, fallback to the normal flow.

Anyway, I won't get too picky since this does the job, but I would recommend a refactor in the future.

2020-02-14 10:32 UTC, AjimenezDCL commented on unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/HUDController.cs
> +    public void ShowWelcomeNotification()
This goes against the whole convention we have been using for the HUDs and specifically for the notifications.

Certainly Kernel should be capable of accessing the needed information to provide a model through the existent `ShowNotificationFromJson` method.

2020-02-14 14:34 UTC, BrianAmadori commented on kernel/packages/decentraland-loader/lifecycle/controllers/download.ts
> +    if (isTutorial()) {
Nailed it. I already have this redesign in a separate branch, but I don't want to expose this for now because we are going to merge it by 2022.

2020-02-14 14:35 UTC, AjimenezDCL commented on kernel/packages/decentraland-loader/lifecycle/controllers/download.ts
> +    if (isTutorial()) {
Keeping the good stuff for yourself :(.

Nice to hear!

2020-02-14 17:55 UTC, pravusjif commented on kernel/packages/decentraland-loader/lifecycle/controllers/download.ts
> +    // stub
I have no idea why that new param is in that constructor XD it precedes my intervention of this PR, I'll update the comment at least

2020-02-14 18:14 UTC, moliva commented on kernel/packages/decentraland-loader/lifecycle/controllers/download.ts
> +    // stub
There is no `TODO` here, but an empty block of code will generate a warning, that's why we have a stub comment.
The constructor is necessary though to set the options field with the required `tutorialBaseURL`.

2020-02-14 18:22 UTC, pravusjif commented on kernel/packages/decentraland-loader/lifecycle/controllers/download.ts
> +    // stub
ok so we will leave it as it is @AjimenezDCL

2020-02-14 20:09 UTC, pravusjif commented on unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/HUDController.cs
> +    public void ShowWelcomeNotification()
I created an issue with all the info to be tackled in the future:
https://app.zenhub.com/workspaces/explorer-5dc988c462b0b700019b0b42/issues/decentraland/explorer/549

2020-02-15 08:14 UTC, AjimenezDCL commented on unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/HUDController.cs
> +    public void ShowWelcomeNotification()
Nice, approving

2020-02-15 08:15 UTC, AjimenezDCL approved these changes

2020-02-15 15:00 UTC, merged