feat: empty parcel simple import from builder
decentraland/explorer pull request #461
Opened 2020-02-01 15:36 UTC by eordano

This allows the following workflow:

0) `make watch` and open http://localhost:8080
A) Build a scene in the builder
B) Download it and unzip it in the folder `kernel/static/loader/empty-parcels`
C) Run `make empty-parcels`
D) Refresh the client to see how it looks like.

2020-02-04 17:00 UTC, BrianAmadori requested changes

2020-02-04 17:00 UTC, BrianAmadori commented on kernel/packages/decentraland-loader/lifecycle/controllers/download.ts
> +    if (!this.emptyScenesPromise) {
This method is supposed to return the scene giving it an `sceneId`. If the first request isn't an empty parcel the logic would break. Without mentioning that it also breaks the contract of the method. There isn't a better way of doing this?

2020-02-04 20:41 UTC, eordano commented on kernel/packages/decentraland-loader/lifecycle/controllers/download.ts
> +    if (!this.emptyScenesPromise) {
This is lazy initialization. This if will be hit only one time, why do you think it breaks the contract?

2020-02-05 13:40 UTC, pravusjif approved these changes

2020-02-05 14:20 UTC, BrianAmadori commented on kernel/packages/decentraland-loader/lifecycle/controllers/download.ts
> +    if (!this.emptyScenesPromise) {
This method is not for initialization, is for retrieving a sceneData using a sceneId by param. If the emptyScenesPromise is not resolved and some scene is fetched, incorrect data will be returned (param will be ignored). Can't this code be moved outside this function? to another method/constructor?

2020-02-05 14:49 UTC, BrianAmadori approved these changes

2020-02-05 14:59 UTC, merged