feat: Content moderation scenes & users
decentraland/explorer pull request #481
Opened 2020-02-05 11:34 UTC by AjimenezDCL

Enabling ReportScenes and Report/Block users

2020-02-10 19:57 UTC, eordano commented on kernel/packages/unity-interface/dcl.ts
> +    const tab = window.open('about:blank', '_blank')
```suggestion
    const tab = window.open(data.url, '_blank')
```

2020-02-10 19:57 UTC, eordano commented on kernel/packages/unity-interface/dcl.ts
> +    tab.location.href = data.url
```suggestion
```

2020-02-10 19:57 UTC, eordano commented on kernel/packages/unity-interface/dcl.ts
> +    const tab = window.open('about:blank', '_blank')
why start with `about:blank`?

2020-02-11 19:43 UTC, BrianAmadori requested changes

2020-02-11 19:43 UTC, BrianAmadori commented on kernel/packages/shared/comms/index.ts
> +        if (!profile!.blocked.includes(user.userId!)) {
Noob question: What does `profile!` mean?

2020-02-11 19:43 UTC, BrianAmadori commented on kernel/packages/unity-interface/dcl.ts
> +      if (profile.blocked) {
Can we unify those ifs to save indenting?

2020-02-11 19:43 UTC, BrianAmadori commented on kernel/packages/unity-interface/dcl.ts
> +    defaultLogger.info('!', profile)
This log is necessary?

2020-02-11 19:43 UTC, BrianAmadori commented on unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/PlayerInfoCardHUD/PlayerInfoCardHUDController.cs
> +        if (!ownUserProfile.blocked.Contains(currentUserProfile.userId))
```suggestion
        if (ownUserProfile.blocked.Contains(currentUserProfile.userId))
            return;
```

2020-02-11 19:43 UTC, BrianAmadori commented on unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/PlayerInfoCardHUD/PlayerInfoCardHUDController.cs
> +        if (ownUserProfile.blocked.Contains(currentUserProfile.userId))
```suggestion
        if (!ownUserProfile.blocked.Contains(currentUserProfile.userId))
            return;
```

2020-02-11 19:43 UTC, BrianAmadori commented on unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/PlayerInfoCardHUD/PlayerInfoCardHUDController.cs
>              currentUserProfile.OnUpdate -= SetUserProfile;
We can use the `?` expression instead of `if` to make the code a bit more brief.
```suggestion
            currentUserProfile?.OnUpdate -= SetUserProfile;
```

2020-02-11 19:43 UTC, BrianAmadori commented on unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/PlayerInfoCardHUD/PlayerInfoCardHUDView.cs
> +        if (IsBlocked(userProfile))
we can make the code more brief here with something like:
```
bool isBlocked = IsBlocked(userProfile);

unblockPlayerButton.gameObject.SetActive(isBlocked);
blockedAvatarOverlay.gameObject.SetActive(isBlocked);
```

2020-02-11 19:43 UTC, BrianAmadori commented on unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/PlayerInfoCardHUD/PlayerInfoCardHUDView.cs
> +        return false;
we should remove all the `Debug.Log` stuff here. (or put under a disabled VERBOSE static bool if really needed)

2020-02-11 19:43 UTC, BrianAmadori commented on unity-client/Assets/Scripts/MainScripts/DCL/UserProfile/UserProfileController.cs
> +        Debug.Log(ownUserProfile.userId);
```suggestion
        
```

2020-02-11 19:43 UTC, BrianAmadori commented on unity-client/Assets/Scripts/MainScripts/DCL/WebInterface/Interface.cs
> +        public static bool VERBOSE = true;
```suggestion
        public static bool VERBOSE = false;
```

2020-02-11 19:43 UTC, BrianAmadori commented on kernel/packages/unity-interface/dcl.ts
> +      global.globalStore.dispatch(saveAvatarRequest({ ...profile, blocked: [...(profile.blocked || []), data.userId] }))
Why we are doing `[...(profile.blocked || []), data.userId]` here? Can we uncompress this semantic a bit more to make it more readable?

2020-02-11 19:43 UTC, BrianAmadori commented on unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/PlayerInfoCardHUD/PlayerInfoCardHUDView.cs
>          this.cardClosedCallback = cardClosedCallback;
Why we aren't doing just `hideCardButton.onClick.AddListener( cardClosedCallback )` here? Why are we wrapping the event twice?

2020-02-11 19:53 UTC, AjimenezDCL commented on unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/PlayerInfoCardHUD/PlayerInfoCardHUDView.cs
> +        return false;
I thinks this branch is still WIP.

2020-02-11 20:12 UTC, belohlavek commented on unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/PlayerInfoCardHUD/PlayerInfoCardHUDController.cs
>              currentUserProfile.OnUpdate -= SetUserProfile;
<img width="816" alt="Screen Shot 2020-02-11 at 17 08 22" src="https://user-images.githubusercontent.com/1307029/74274896-a195cd80-4cf1-11ea-90fd-c02761401942.png">

2020-02-12 00:41 UTC, eordano commented
Weird behavior on skin color:

![image](https://user-images.githubusercontent.com/42750/74292602-3232d480-4d17-11ea-9000-6c14501472cc.png)

2020-02-12 00:42 UTC, eordano commented
Also, NPE on dancing from a blocked user:

![image](https://user-images.githubusercontent.com/42750/74292678-63aba000-4d17-11ea-84b7-19d96f1814f1.png)

2020-02-12 00:43 UTC, eordano commented
`GET https://peer.decentraland.org/content/contents/body.png 404 (Not Found)`

2020-02-12 08:33 UTC, AjimenezDCL commented on unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/PlayerInfoCardHUD/PlayerInfoCardHUDView.cs
>          this.cardClosedCallback = cardClosedCallback;
I liked it this way more, so we dont have to force a RemoveAllListeners on each Initialize. I find it more elegant since the buttons are setup in the Awake and forgotten for the rest of the lifecycle.

Anyway I think I'm going to change it, it's just adding complexity without being really needed.

2020-02-12 19:55 UTC, pravusjif approved these changes

2020-02-14 20:12 UTC, pravusjif approved these changes

2020-02-15 15:16 UTC, BrianAmadori approved these changes

2020-02-17 16:07 UTC, merged