feat: message of the day
decentraland/explorer pull request #488
Opened 2020-02-06 18:04 UTC by BrianAmadori

2020-02-07 08:38 UTC, AjimenezDCL requested changes

2020-02-07 08:38 UTC, AjimenezDCL commented on unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/WelcomeHUD/WelcomeHUDController.cs
> +        view.closeButton.onClick.AddListener(Close);
I think this should be in `WelcomeHUDView`. We could have a `WelcomeHUDView.Initialize(Action confirmCallback, Action closeCallback);`

2020-02-07 08:38 UTC, AjimenezDCL commented on unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/WelcomeHUD/WelcomeHUDController.cs
> +        view.closeButton.onClick.RemoveAllListeners();
I'd change this for `UnityEngine.Object.Destroy(view.gameObject);`. Buttons will be destroyed as well and callbacks will become irrelevant.

2020-02-07 15:49 UTC, AjimenezDCL approved these changes

2020-02-10 08:54 UTC, AjimenezDCL approved these changes

2020-02-11 08:38 UTC, AjimenezDCL requested changes

2020-02-11 08:38 UTC, AjimenezDCL commented on kernel/packages/unity-interface/dcl.ts
> +      // TODO(Brian): Teleport player to desired location
Is this comment needed?

2020-02-11 08:38 UTC, AjimenezDCL commented on unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/WelcomeHUD/WelcomeHUDController.cs
> +        public bool hasWallet; //TODO(Brian): Use WEB3 param in userProfile
This is already implemented in `feat/marketplace_link`. If this branch is merged first I will change it myself, otherwise we can update this.

2020-02-11 08:38 UTC, AjimenezDCL commented on unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/WelcomeHUD/WelcomeHUDView.cs
> +            return;
I would remove the param `model` and do this check in the controller.

2020-02-11 13:36 UTC, moliva approved these changes

2020-02-11 13:36 UTC, moliva commented on kernel/packages/shared/world/TeleportController.ts
> +    }
You could simplify this to:
```suggestion
    const tpMessage: string = teleportMessage ? teleportMessage : `Teleporting to ${x}, ${y}...`
```

2020-02-11 13:54 UTC, BrianAmadori commented on kernel/packages/shared/world/TeleportController.ts
> +    }
Not sure if agree, I see it as harder to read. 

More compact != better.

2020-02-11 14:10 UTC, moliva commented on kernel/packages/shared/world/TeleportController.ts
> +    }
Sure, I agree. It has more to do with immutability and typing in this case, either was it's just a suggestion.

2020-02-11 14:32 UTC, BrianAmadori commented on kernel/packages/shared/world/TeleportController.ts
> +    }
Oh, I didn't see the `const` bit. With the logic as it is `tpMessage` won't work as a const because is overriden by the error message below, but that can be another const. Let me check, maybe I can improve on this a bit.

2020-02-11 14:33 UTC, BrianAmadori commented on kernel/packages/unity-interface/dcl.ts
> +      // TODO(Brian): Teleport player to desired location
Not anymore. Removing it.

2020-02-11 15:11 UTC, pravusjif requested changes

2020-02-11 15:11 UTC, pravusjif commented on unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/WelcomeHUD/WelcomeHUDView.cs
> +    private const string PREFAB_PATH_NO_WALLET = "WelcomeNoWalletHUD";
I think it's better if we have the prefab gameobject references here as we do in other places

2020-02-11 15:11 UTC, pravusjif commented on unity-client/Assets/Scripts/MainScripts/Debugging/WSS/WSSController.cs
> +                    $"{baseUrl}{debugString}{debugPanelString}position={startInCoords.x}%2C{startInCoords.y}&ws=ws%3A%2F%2Flocalhost%3A5000%2Fdcl&STATIC_WORLD&AWS");
do we want these 2 new params always?

2020-02-11 18:22 UTC, BrianAmadori commented on unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/WelcomeHUD/WelcomeHUDView.cs
> +    private const string PREFAB_PATH_NO_WALLET = "WelcomeNoWalletHUD";
This makes sense, but it can't be done easily. The view is actually instanced by the controller in the static method `WelcomeHUDView.CreateView`. The controller is not a MonoBehaviour, so it can't hold the references.

This is the pattern we are using in all HUD elements. If we want to use prefab references (and I agree this'd be the optimal way of doing this) we would have to implement a factory for all of them. I'd apply this refactor in another PR.

2020-02-11 18:23 UTC, BrianAmadori commented on unity-client/Assets/Scripts/MainScripts/Debugging/WSS/WSSController.cs
> +                    $"{baseUrl}{debugString}{debugPanelString}position={startInCoords.x}%2C{startInCoords.y}&ws=ws%3A%2F%2Flocalhost%3A5000%2Fdcl&STATIC_WORLD&AWS");
we don't, gonna remove them

2020-02-11 18:42 UTC, AjimenezDCL approved these changes

2020-02-11 19:09 UTC, pravusjif approved these changes

2020-02-11 19:53 UTC, merged