fix: triangles count metrics
decentraland/explorer pull request #57
Opened 2019-11-12 18:16 UTC by pbosio

Count amount of triangles even if mesh is already in memory.
Closes #18

2019-11-12 18:37 UTC, BrianAmadori requested changes
Remember to update the tests

2019-11-13 07:52 UTC, javiermaria approved these changes

2019-11-13 12:39 UTC, javiermaria approved these changes

2019-11-13 14:45 UTC, nearnshaw commented
@BrianAmadori . @pbosio    
from what I understand, tests won't be able work until we fix all of the ones that Pravus was working on, right?
This fix is a blocker for shipping the Unity-based Builder, which is supposed to go out this week
Any chance we can leave the tests for later?

2019-11-13 17:45 UTC, pravusjif commented on unity-client/Assets/Scripts/MainScripts/DCL/Controllers/Scene/SceneMetricsController.cs
> +                    model.triangles -= mf.sharedMesh.triangles.Length / 3;
Why are we dividing by 3 the triangles instead of the vertices?

2019-11-13 17:52 UTC, javiermaria commented on unity-client/Assets/Scripts/MainScripts/DCL/Controllers/Scene/SceneMetricsController.cs
> +                    model.triangles -= mf.sharedMesh.triangles.Length / 3;
Following that, the number of vertices in a model is not `triangles / 3` unless the model consists of completely detached triangles - there will always be shared vertices between triangles.

2019-11-13 17:58 UTC, pravusjif commented on unity-client/Assets/Scripts/MainScripts/DCL/Controllers/Scene/SceneMetricsController.cs
> +                    model.triangles -= mf.sharedMesh.triangles.Length / 3;
Also, we should actually just use `mf.sharedMesh.triangles.Length` right? no division at all

2019-11-13 18:49 UTC, pravusjif approved these changes

2019-11-13 19:03 UTC, javiermaria approved these changes

2019-11-13 19:30 UTC, BrianAmadori commented on unity-client/Assets/Scripts/MainScripts/DCL/Controllers/Scene/SceneMetricsController.cs
> +                    model.triangles -= mf.sharedMesh.triangles.Length / 3;
Yep, I think I initially though this was referring to vertices for some reason and added the `/ 3` but Javi is right. Its makes no sense.

2019-11-14 17:03 UTC, BrianAmadori approved these changes

2019-11-14 17:03 UTC, merged