fix: Canvas scaler match change from 0 to 1
decentraland/explorer pull request #585
Opened 2020-02-18 21:39 UTC by RominaMarchetti

# What?
_Canvas scaler match_ changed from 0 to 1

# Why? 
Because it was colliding with the chat window. This way won't happen again.

2020-02-18 21:40 UTC, BrianAmadori approved these changes

2020-02-18 22:16 UTC, pbosio requested changes
Emotes' icon scales correctly but it's misplaced (it's behind chat window)

2020-02-19 01:48 UTC, pravusjif approved these changes
After addressing pato's request it should be fine

2020-02-19 12:27 UTC, RominaMarchetti commented
@pbosio @pravusjif  ready for review again.

2020-02-19 12:58 UTC, pbosio approved these changes

2020-02-19 13:15 UTC, merged