fix: made all our shaders srp batcher compatible
decentraland/explorer pull request #636
Opened 2020-02-21 18:58 UTC by BrianAmadori

This should save a lot of draw calls.

2020-02-21 20:10 UTC, BrianAmadori commented
Just tested in min specs, around 0,0:ORG, chrome, ubuntu:
Master -> 20-25 fps
This PR -> 25-30 fps

2020-02-21 20:23 UTC, AjimenezDCL approved these changes

2020-02-21 20:47 UTC, BrianAmadori commented
Sorry, the ~30 ish improvement was on medium quality. On basic quality around that same zone the FPS go up to 40.

2020-02-21 23:00 UTC, pbosio approved these changes

2020-02-26 08:53 UTC, AjimenezDCL approved these changes

2020-02-26 08:53 UTC, AjimenezDCL commented on unity-client/Assets/Scripts/MainScripts/DCL/Controllers/MaterialTransitionController/MaterialTransitionController.cs
> +    //static MaterialPropertyBlock placeholderPropertyBlock;
Remove all the comments

2020-02-26 13:46 UTC, pbosio approved these changes

2020-02-26 21:23 UTC, pravusjif requested changes
we still got problems with transparency
https://play.decentraland.zone/branch/fix/lit-shader-not-srp-compatible-issue/index.html?ENV=zone&position=55%2C-71&realm=odin-amber

2020-02-27 01:00 UTC, pravusjif approved these changes

2020-02-27 15:26 UTC, merged