fix: unit tests should pass again #1018
decentraland/explorer pull request #65
Opened 2019-11-13 16:32 UTC by pravusjif

2019-11-26 12:32 UTC, pravusjif commented
- Failing tests:
     + SceneTests -> the coroutine processing the messages in the Global Scene bus is stopping mid-test, we still don't know why. The tests pass individually
    + LoadableShapesTests -> GLTFShape_Tests -> PreExistentShapeUpdate
    + LoadableShapesTests -> Tests -> LoadableShapesTests -> PreExistentShapeUpdate
    + MaterialTransitionControllertests -> MaterialTransitionWithGLTF
    + MaterialTransitionControllertests -> MaterialTransitionWithParametrizableMeshes
    + AudioTests -> Tests -> AudioTests -> AudioComponentMissingValuesGetDefaultedOnUpdate
    + BillboardTests -> Tests -> BillboardTests -> CheckLookAtPlayer
    + AvatarShape_Tests -> Tests -> AvatarShapeTests -> NameBackgroundHasCorrectSize
    + AvatarShape_Tests -> Tests -> AvatarShapeVisualTests (I didn't even run it as we already know the problems we have with visual tests today)
    + UIContainerRectTests -> Tests -> UIContainerRectTests -> TestParenting
    + VisualTests (I didn't run them as we already know the problems we have with visual tests today)

-----------------------

* The “PreExistentShapeUpdate” that fail report the same error (something about loading the damaged helmet gltf), and apparently we have 2 sets of the same GLTf tets, maybe we can remove one of the 2 sets.
* “MaterialTransitionControllertests” report a null reference exception
* The Audio test reports a wrongly asserted float
* The billboard test reports a problem with the used model
* “AvatarShape_Tests” reports a problem with the avatar name size
* “UIContainerRectTests” reports a wrongly asserted bool

2019-12-04 19:25 UTC, BrianAmadori requested changes

2019-12-04 19:25 UTC, BrianAmadori commented on unity-client/Assets/Scripts/MainScripts/DCL/Components/Avatar/Tests/AvatarShapeTests.cs
> +    /* public class AvatarShapeVisualTests : VisualTestsBase
We should disable visual tests using the `.asmdef` settings and uncomment this code. (or remove this code if applicable).

2019-12-04 19:25 UTC, BrianAmadori commented on unity-client/Assets/Scripts/MainScripts/DCL/Components/UI/UIScreenSpace/Tests/UIScreenSpaceTests.cs
> +            yield return yieldInstruction;
Here is more readable to use `yield return TestHelpers.SharedComponentUpdate(...`

2019-12-04 19:25 UTC, BrianAmadori commented on unity-client/Assets/Scripts/MainScripts/DCL/Components/UI/UIScreenSpace/Tests/UIScreenSpaceTests.cs
> +            TestHelpers.SetCharacterPosition(Vector3.zero);
Here is more readable to use yield return `TestHelpers.SharedComponentUpdate`.

2019-12-04 19:25 UTC, BrianAmadori commented on unity-client/Assets/Scripts/MainScripts/DCL/Components/UI/UIScrollRect/Tests/UIScrollRectTests.cs
> +                height = new UIValue(30, UIValue.Unit.PERCENT)
Here is more readable to use `yield return TestHelpers.SharedComponentUpdate`

2019-12-04 19:25 UTC, BrianAmadori commented on unity-client/Assets/Scripts/MainScripts/DCL/Components/UI/UITestsBase.cs
> +        protected override IEnumerator InitScene(bool usesWebServer = false, bool spawnCharController = true, bool spawnTestScene = true, bool spawnUIScene = true, bool debugMode = false, bool reload
`reloadUnityScene` argument seems to be not used in this method. I'm missing something?

2019-12-04 19:25 UTC, BrianAmadori commented on unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/Minimap/Tests/MinimapHUDTests.cs
> +            Assert.IsTrue(Reflection_GetField<TextMeshProUGUI>(view, "sceneNameText").text == "Unnamed");
I think `Assert.AreEqual` would give a better debug info when this test fails.

2019-12-04 19:25 UTC, BrianAmadori commented on unity-client/Assets/Scripts/MainScripts/DCL/Controllers/MaterialTransitionController/Tests/MaterialTransitionControllerTests.cs
> +        // }
We should remove commented code.

2019-12-04 19:25 UTC, BrianAmadori commented on unity-client/Assets/Scripts/MainScripts/DCL/Controllers/Minimap/Test/MinimapTest.cs
> +            var minimapCamera = GameObject.Instantiate(Resources.Load<GameObject>("Minimap")).GetComponentInChildren<MinimapCamera>();
I should split this statement in many lines (and extract to another method if applicable). If this throws an exception we wouldn't infer which one of those expressions is the cause of it.

2019-12-04 19:25 UTC, BrianAmadori commented on unity-client/Assets/Scripts/MainScripts/DCL/Controllers/Minimap/Test/MinimapTest.cs
>              InitScene();
This shouldn't be `yield return InitScene();` ?

2019-12-04 19:25 UTC, BrianAmadori commented on unity-client/Assets/Scripts/MainScripts/DCL/Controllers/Minimap/Test/MinimapTest.cs
> +            var minimapCamera = GameObject.Instantiate(Resources.Load<GameObject>("Minimap")).GetComponentInChildren<MinimapCamera>();
I should split this statement in many lines (and extract to another method if applicable). If this throws an exception we wouldn't infer which one of those expressions is the cause of it.

2019-12-04 19:25 UTC, BrianAmadori commented on unity-client/Assets/Scripts/MainScripts/DCL/Controllers/Minimap/Test/MinimapTest.cs
> +            var minimapCamera = GameObject.Instantiate(Resources.Load<GameObject>("Minimap")).GetComponentInChildren<MinimapCamera>();
I should split this statement in many lines (and extract to another method if applicable). If this throws an exception we wouldn't infer which one of those expressions is the cause of it.

2019-12-04 19:25 UTC, BrianAmadori commented on unity-client/Assets/Scripts/MainScripts/DCL/Controllers/Scene/SceneBoundariesController/Tests/SceneBoundariesCheckerTests.cs
>              TestHelpers.InstantiateEntityWithShape(scene, entityId, DCL.Models.CLASS_ID.BOX_SHAPE, Vector3.zero);
To simplify, we can use `TestHelpers.CreateEntityWithBoxShape` here.

2019-12-04 19:25 UTC, BrianAmadori commented on unity-client/Assets/Scripts/MainScripts/DCL/Controllers/Scene/SceneBoundariesController/Tests/SceneBoundariesCheckerTests.cs
>              TestHelpers.CreateSceneEntity(scene, entityId);
We can avoid the `entityId` using `TestHelpers.CreateSceneEntity(scene)` override, as this returns an entity with an auto-generated id.

2019-12-04 19:25 UTC, BrianAmadori commented on unity-client/Assets/Scripts/MainScripts/DCL/Controllers/Scene/SceneBoundariesController/Tests/SceneBoundariesCheckerTests.cs
>              TestHelpers.CreateSceneEntity(scene, entityId);
We can avoid the `entityId` using `TestHelpers.CreateSceneEntity(scene)` override, as this returns an entity with an auto-generated id.

2019-12-04 19:25 UTC, BrianAmadori commented on unity-client/Assets/Scripts/MainScripts/DCL/Controllers/Scene/SceneBoundariesController/Tests/SceneBoundariesCheckerTests.cs
>              TestHelpers.InstantiateEntityWithShape(scene, entityId, DCL.Models.CLASS_ID.BOX_SHAPE, new Vector3(18, 1, 18));
To simplify, we can use TestHelpers.CreateEntityWithBoxShape here.

2019-12-04 19:25 UTC, BrianAmadori commented on unity-client/Assets/Scripts/MainScripts/DCL/Controllers/Scene/SceneBoundariesController/Tests/SceneBoundariesCheckerTests.cs
>              TestHelpers.CreateSceneEntity(scene, entityId);
We can avoid the `entityId` using `TestHelpers.CreateSceneEntity(scene)` override, as this returns an entity with an auto-generated id.

2019-12-04 19:25 UTC, BrianAmadori commented on unity-client/Assets/Scripts/MainScripts/DCL/Controllers/Scene/SceneBoundariesController/Tests/SceneBoundariesCheckerTests.cs
>              TestHelpers.CreateSceneEntity(scene, entityId);
Same as the rest of the comments.

2019-12-04 19:25 UTC, BrianAmadori commented on unity-client/Assets/Scripts/MainScripts/DCL/Controllers/Scene/SceneBoundariesController/Tests/SceneBoundariesCheckerTests.cs
> +            // yield return null;
We should remove this commented line if applicable.

2019-12-04 19:25 UTC, BrianAmadori commented on unity-client/Assets/Scripts/MainScripts/DCL/Controllers/Scene/SceneBoundariesController/Tests/SceneBoundariesCheckerTests.cs
>              TestHelpers.CreateSceneEntity(scene, entityId);
Same as the rest of the comments.

2019-12-04 19:25 UTC, BrianAmadori commented on unity-client/Assets/Scripts/MainScripts/DCL/Controllers/Scene/SceneBoundariesController/Tests/SceneBoundariesCheckerTests.cs
>              TestHelpers.InstantiateEntityWithShape(scene, entityId, DCL.Models.CLASS_ID.BOX_SHAPE, new Vector3(8, 5, 8));
We can simplify using `CreateEntityWithBoxShape` here.

2019-12-04 19:25 UTC, BrianAmadori commented on unity-client/Assets/Scripts/MainScripts/DCL/Helpers/TestHelpers.cs
> +            yield return yieldInstruction;
We can just yield return the `TestHelpers.SharedComponentUpdate` to simplify.

2019-12-04 19:26 UTC, BrianAmadori commented
On top of those requests. I'm not very confident about the `ParcelScene` initialization changes. Going to review it more in depth later.

2019-12-09 14:01 UTC, pravusjif commented on unity-client/Assets/Scripts/MainScripts/DCL/Components/Avatar/Tests/AvatarShapeTests.cs
> +    /* public class AvatarShapeVisualTests : VisualTestsBase
separated the avatarshape tests into a new assmebly

2019-12-09 16:48 UTC, pravusjif commented on unity-client/Assets/Scripts/MainScripts/DCL/Components/UI/UIScreenSpace/Tests/UIScreenSpaceTests.cs
> +            yield return yieldInstruction;
done

2019-12-09 16:56 UTC, pravusjif commented on unity-client/Assets/Scripts/MainScripts/DCL/Components/UI/UIScreenSpace/Tests/UIScreenSpaceTests.cs
> +            TestHelpers.SetCharacterPosition(Vector3.zero);
done

2019-12-09 16:56 UTC, pravusjif commented on unity-client/Assets/Scripts/MainScripts/DCL/Components/UI/UIScrollRect/Tests/UIScrollRectTests.cs
> +                height = new UIValue(30, UIValue.Unit.PERCENT)
done

2019-12-09 16:59 UTC, pravusjif commented on unity-client/Assets/Scripts/MainScripts/DCL/Components/UI/UITestsBase.cs
> +        protected override IEnumerator InitScene(bool usesWebServer = false, bool spawnCharController = true, bool spawnTestScene = true, bool spawnUIScene = true, bool debugMode = false, bool reload
fixed

2019-12-09 17:06 UTC, pravusjif commented on unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/Minimap/Tests/MinimapHUDTests.cs
> +            Assert.IsTrue(Reflection_GetField<TextMeshProUGUI>(view, "sceneNameText").text == "Unnamed");
done

2019-12-09 17:16 UTC, pravusjif commented on unity-client/Assets/Scripts/MainScripts/DCL/Controllers/Minimap/Test/MinimapTest.cs
> +            var minimapCamera = GameObject.Instantiate(Resources.Load<GameObject>("Minimap")).GetComponentInChildren<MinimapCamera>();
done

2019-12-09 17:18 UTC, pravusjif commented on unity-client/Assets/Scripts/MainScripts/DCL/Controllers/Minimap/Test/MinimapTest.cs
>              InitScene();
yes, corrected it

2019-12-09 17:18 UTC, pravusjif commented on unity-client/Assets/Scripts/MainScripts/DCL/Controllers/Minimap/Test/MinimapTest.cs
> +            var minimapCamera = GameObject.Instantiate(Resources.Load<GameObject>("Minimap")).GetComponentInChildren<MinimapCamera>();
done

2019-12-09 17:18 UTC, pravusjif commented on unity-client/Assets/Scripts/MainScripts/DCL/Controllers/Minimap/Test/MinimapTest.cs
> +            var minimapCamera = GameObject.Instantiate(Resources.Load<GameObject>("Minimap")).GetComponentInChildren<MinimapCamera>();
done

2019-12-09 17:29 UTC, pravusjif commented on unity-client/Assets/Scripts/MainScripts/DCL/Controllers/Scene/SceneBoundariesController/Tests/SceneBoundariesCheckerTests.cs
>              TestHelpers.InstantiateEntityWithShape(scene, entityId, DCL.Models.CLASS_ID.BOX_SHAPE, Vector3.zero);
Done

2019-12-09 18:05 UTC, pravusjif commented on unity-client/Assets/Scripts/MainScripts/DCL/Controllers/Scene/SceneBoundariesController/Tests/SceneBoundariesCheckerTests.cs
>              TestHelpers.CreateSceneEntity(scene, entityId);
Applied to many scene boundaries tests

2019-12-09 18:16 UTC, pravusjif commented on unity-client/Assets/Scripts/MainScripts/DCL/Helpers/TestHelpers.cs
> +            yield return yieldInstruction;
done

2019-12-09 19:00 UTC, BrianAmadori approved these changes

2019-12-10 06:28 UTC, AjimenezDCL requested changes

2019-12-10 06:28 UTC, AjimenezDCL commented on unity-client/Assets/Scripts/MainScripts/DCL/Controllers/DCLCharacterController.cs
> +    float originalGravity;
Offtopic question:
If I remember correctly Unity's CharacterController already gives gravity support. Why are we not using it? It would lead to a more elegant code without workarounds like this.

2019-12-10 06:28 UTC, AjimenezDCL commented on unity-client/Assets/Scripts/Tests/TestsBase.cs
> +    protected Vector2 CalculateAlignedAnchoredPosition(Rect parentRect, Rect elementRect, string vAlign = "center", string hAlign = "center")
This is only being used by UITests. Can we move this method to `UITestBase`?

2019-12-10 12:23 UTC, pravusjif commented on unity-client/Assets/Scripts/MainScripts/DCL/Controllers/DCLCharacterController.cs
> +    float originalGravity;
Unity's charactercontroller doesn't have any gravity functionality

2019-12-10 12:27 UTC, pravusjif commented on unity-client/Assets/Scripts/Tests/TestsBase.cs
> +    protected Vector2 CalculateAlignedAnchoredPosition(Rect parentRect, Rect elementRect, string vAlign = "center", string hAlign = "center")
Sure thing, done

2019-12-10 12:29 UTC, AjimenezDCL approved these changes

2019-12-10 13:36 UTC, merged