feat: navmap basic features
decentraland/explorer pull request #746
Opened 2020-03-17 16:56 UTC by pravusjif

2020-03-24 03:48 UTC, pbosio commented
Just one comment: Avatar Emotes icon is appearing over NavMap

<img width="295" alt="Screen Shot 2020-03-24 at 00 46 33" src="https://user-images.githubusercontent.com/4195708/77386176-f9037080-6d68-11ea-8160-2570ba64f1b3.png">

2020-03-24 03:48 UTC, pbosio approved these changes

2020-03-25 12:48 UTC, RominaMarchetti commented
@pbosio that issue exceeds the nav map. We need to find a way to fix this because now canvas layers are ignoring their order (don't know why). This is noticeable in every full screen UI panel (with creators' scenes UI is the same :( ).

2020-03-25 17:37 UTC, BrianAmadori requested changes
Found the following issues:

- When opening and closing the nav map, the minimap is displayed incorrectly (see screenshot below):
![image](https://user-images.githubusercontent.com/6875814/77567332-c27f4000-6ea5-11ea-9e10-6336555b0a55.png)

- Nav-map is not centered correctly when opening it.

- Scrolling input issues are all over the place, drag has too much momentum and sensivity is too low . (We can fix those issues as part of the scrolling issue, tho)

2020-03-26 16:12 UTC, BrianAmadori approved these changes

2020-03-26 21:27 UTC, merged