feat: support animated (gif) picture frames
decentraland/explorer pull request #880
Opened 2020-05-09 01:14 UTC by pbosio

- added plugin to support decode gif binary.
- modified `NFTShapeLoaderController` class to load animated picture frames.

test scene: `-103.102.nft`

2020-05-11 13:53 UTC, pravusjif approved these changes

2020-05-15 14:33 UTC, BrianAmadori requested changes

2020-05-15 14:33 UTC, BrianAmadori commented on unity-client/Assets/Scripts/MainScripts/DCL/Components/LoadableShapes/NFTShape/NFTShapeLoaderController.cs
> +        private Texture2D _texture;
```suggestion
        public Texture2D texture { get; private set; }
```

2020-05-15 14:33 UTC, BrianAmadori commented on unity-client/Assets/Scripts/MainScripts/DCL/Components/LoadableShapes/NFTShape/NFTShapeLoaderController.cs
> +        DCLGif _gif;
```suggestion
        DCLGif gif;
```

2020-05-15 14:33 UTC, BrianAmadori commented on unity-client/Assets/Scripts/MainScripts/DCL/Components/LoadableShapes/NFTShape/NFTShapeLoaderController.cs
> +        Coroutine _updateRoutine = null;
```suggestion
        Coroutine updateRoutine = null;
```

2020-05-15 14:33 UTC, BrianAmadori commented on unity-client/Assets/Scripts/MainScripts/DCL/Components/LoadableShapes/NFTShape/NFTShapeLoaderController.cs
> +            _gif = gif;
```suggestion
            this.gif = gif;
```

2020-05-15 14:33 UTC, BrianAmadori commented on unity-client/Assets/UniGif/Example/Script/UniGifImage.cs
> +﻿/*
The example scripts have to be added to the project? We can't remove them?

2020-05-15 14:33 UTC, BrianAmadori commented on unity-client/Assets/UniGif/Example/Script/Utility/UniGifImageAspectController.cs
> +public class UniGifImageAspectController : MonoBehaviour
Can we move the `UniGif` folder to `Plugins`?

2020-05-15 14:33 UTC, BrianAmadori commented on unity-client/Assets/Scripts/MainScripts/DCL/Components/LoadableShapes/NFTShape/NFTShapeLoaderController.cs
> +            _updateRoutine = CoroutineStarter.Start(_gif.UpdateRoutine());
We shouldn't be stopping this coroutine if its already running?

2020-05-15 14:33 UTC, BrianAmadori commented on unity-client/Assets/Scripts/MainScripts/DCL/Components/LoadableShapes/NFTShape/NFTShapeLoaderController.cs
> +    class NFTGifAsset : INFTAsset
Why are we using the `NFT` moniker here? This means we can't use this code for a non-NFT gif component? If we can, we should choose a more generic name.

2020-05-20 13:23 UTC, BrianAmadori approved these changes

2020-05-20 13:47 UTC, merged