fix: Image of a NFTShape disappearing
decentraland/explorer pull request #92
Opened 2019-11-14 19:41 UTC by pbosio

Specially in builder, after placing two NFTShape and then removing one of them, the image of the PictureFrame goes missing. 
Solved by caching the image texture.

2019-11-14 20:21 UTC, pravusjif approved these changes

2019-11-16 17:04 UTC, eordano approved these changes

2019-11-19 16:22 UTC, oOZakMcKrackeNOo approved these changes

2019-11-19 16:27 UTC, BrianAmadori requested changes
Please add a test to validate this fix. It should be relatively easy to achieve.

2019-11-19 16:27 UTC, BrianAmadori commented on unity-client/Assets/Scripts/MainScripts/DCL/Components/LoadableShapes/NFTShape/NFTShapeLoaderController.cs
> +                nftImageTexture = downloadedTex;
I think i liked better the previous method signature. As we could just assign `nftImageTexture` there once, instead of having this call repeated many times across `FetchTexture` calls.

2019-11-19 16:27 UTC, BrianAmadori commented on unity-client/Assets/Scripts/MainScripts/DCL/Components/LoadableShapes/NFTShape/NFTShapeLoaderController.cs
> +    Texture nftImageTexture;
Remember downloaded Texture resources aren't tracked by unity like common `UnityEngine.Object`. They must be released manually unless `Resources.UnloadUnusedAssets` is called.

This said, we are missing a `Destroy(nftImageTexture)` on a `OnDestroy` method here. This'd ensure textures aren't leaking when the object is destroyed.

2019-11-19 18:35 UTC, pbosio commented on unity-client/Assets/Scripts/MainScripts/DCL/Components/LoadableShapes/NFTShape/NFTShapeLoaderController.cs
> +                nftImageTexture = downloadedTex;
done

2019-11-19 18:35 UTC, pbosio commented on unity-client/Assets/Scripts/MainScripts/DCL/Components/LoadableShapes/NFTShape/NFTShapeLoaderController.cs
> +    Texture nftImageTexture;
done & done

2019-11-21 22:23 UTC, BrianAmadori approved these changes

2019-11-22 14:03 UTC, merged